AI-JADEDEVS4/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Number_Closed_Lost_Opportunities__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of closed lost opportunities owned by the current partner account</description>
        <label>Number Closed Lost Opportunities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_Closed_Opportunities__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of closed opportunities owned by the current partner account</description>
        <label>Number Closed Opportunities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_Closed_Won_Opportunities__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of closed won opportunities owned by the current partner account</description>
        <label>Number Closed Won Opportunities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Open_New_Opportunities__c</fullName>
        <label>Number of Open New Opportunities</label>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>Closed Won, Closed Lost, Disqualified, Closed Won - Installments, Closed Non-Pursuit</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.Type</field>
            <operation>equals</operation>
            <value>New</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Open_Opportunities__c</fullName>
        <label>Number of Open Opportunities</label>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>Closed Won, Closed Lost, Disqualified, Closed Won - Installments, Closed Non-Pursuit</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/MigrationContactsToLead.cls
/**@@
#CLASS NAME    :    MigrationContactsToLead
#DESCRIPTION           :    Migrating contacts to Lead based on conditions.   
@@**/
public class MigrationContactsToLead{
    
    /**@@
    #DESCRIPTION   : To create new Account Team member with 'SDR' team role.
    #Paramaters        : trigger.newMap,trigger.oldMap
    @@**/
    public static void moveContactsToLead(List<Account> newList){
        try{
            for(Account accObj : newList){
                //if(Number_Closed_Lost_Opportunities__c, Number_Closed_Opportunities__c, Number_Closed_Won_Opportunities__c, Number_of_Open_New_Opportunities__c, Number_of_Open_Opportunities__c)
            }
        }
        Catch(Exception e){
            System.debug('********'+e);
        }
    }//END OF METHOD
}//END OF CLASS