AI-JADEDEVS4/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Partner Contact who submitted this Lead.</description>
        <inlineHelpText>The Partner Contact who submitted this Lead.</inlineHelpText>
        <label>Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Partner Contact)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Partner Contact who submitted the Lead this Contact was converted from.</inlineHelpText>
        <label>Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Partner Contact who submitted this Lead.</inlineHelpText>
        <label>Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Last_Activity_Date__c</fullName>
        <label>Partner Last Activity Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/BatchExecLeadExpirationNotification_Test.cls
/**@@
#CLASS NAME     :   BatchExecLeadExpirationNotification_Test
#DESCRIPTION    :   This is a test class for BatchExecLeadExpirationNotification batch class & ScheduleLeadExpirationNotification Schedular class.
@@**/

@isTest
    public class BatchExecLeadExpirationNotification_Test {        
    /**@@
    #DESCRIPTION     : Creating test records
    #Paramaters      : None
    @@**/
    @testSetup static void setup() {
        //Insert custom settings
        DataFactory.insertCustomSetting();
        
        // Create Test Account record
        List<Account> oacc = DataFactory.createAccountTestRecords('Test Account', 1);
        
        // Create Test Contact record
        List<Contact> ocon = DataFactory.createContactTestRecords('Test contact',oacc[0].ID ,1);
           
        // Create Test Lead record
        list<Lead> lstLead=DataFactory.createLeadTestRecords('Test',1);
        
        
        list<Lead>  lstLead1= DataFactory.createLeadTestRecords('test',1);
        lstLead1[0].Partner_Contact__c = ocon[0].id;
        lstLead1[0].Partner_Last_Activity_Date__c = System.today()-53;
        update lstLead1;
        
    }    
        
    /**@@
    #DESCRIPTION     : This is a test method used to create test data for BatchDailySummary batch class.
    #Paramaters      : None
    @@**/
    static testMethod void LeadExpirationNotification_test(){

        Test.StartTest();
        
		Database.executeBatch(new BatchExecLeadExpirationNotification());
		
        Test.stopTest();
    }//End of DailySummary_test
    
    /**@@
    #DESCRIPTION     : This is  method used to test and schedule batch class
    #Paramaters      : SchedulableContext ctx
    @@**/    
    static testMethod void ScheduleLeadExpirationNotification_test(){
        ScheduleLeadExpirationNotification objschclass = new ScheduleLeadExpirationNotification();
        String cronexpression ='0 0 9 * * ? *';
        system.schedule('BatchExecOppExpirationNotification', cronexpression, objschclass);
    }//end of method
 }//End of classs