AI-JADEDEVS4/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Budgeted_Project__c</fullName>
        <label>Budgeted Project</label>
        <picklist>
            <picklistValues>
                <fullName>Needs Justification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_System__c</fullName>
        <label>CRM</label>
        <picklist>
            <picklistValues>
                <fullName>Microsoft Dynamics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Netsuite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oracle - Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oracle - PeopleSoft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oracle-RightNow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oracle - Siebel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SugarCRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sage</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_End__c</fullName>
        <description>Enter the prospects Year End.  This is the end of their financial year.</description>
        <label>Fiscal Year End</label>
        <picklist>
            <picklistValues>
                <fullName>Jan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jul</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aug</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nov</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dec</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HR_System__c</fullName>
        <label>HR</label>
        <picklist>
            <picklistValues>
                <fullName>ADP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BambooHR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceridian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL Vendor (See GL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Namely</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paycor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paylocity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleSoft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TriNet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MDF_Sourced_Lead__c</fullName>
        <label>MDF Sourced Lead</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Partner Contact who submitted this Lead.</description>
        <inlineHelpText>The Partner Contact who submitted this Lead.</inlineHelpText>
        <label>Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Partner Contact)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Frame__c</fullName>
        <label>Time Frame</label>
        <picklist>
            <picklistValues>
                <fullName>1 - 3 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - 6 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 - 12 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13 - 24 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Time Frame</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Budgeted_Project__c</fullName>
        <label>Budgeted Project</label>
        <picklist>
            <picklistValues>
                <fullName>Needs Justification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_End__c</fullName>
        <label>Fiscal Year End</label>
        <picklist>
            <picklistValues>
                <fullName>Jan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jul</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aug</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nov</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dec</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MDF_Approval_Number__c</fullName>
        <label>MDF Approval Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDF_Sourced_Lead__c</fullName>
        <label>MDF Sourced Lead</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Partner Contact who submitted the Lead this Contact was converted from.</inlineHelpText>
        <label>Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_change_Pain_Points__c</fullName>
        <label>Reason for change/Pain Points</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Time_Frame__c</fullName>
        <label>Time Frame</label>
        <picklist>
            <picklistValues>
                <fullName>1 - 3 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - 6 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 - 12 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13 - 24 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Time Frame</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Budgeted_Project__c</fullName>
        <inlineHelpText>Is the project budgeted?</inlineHelpText>
        <label>Budgeted Project</label>
        <picklist>
            <picklistValues>
                <fullName>Needs Justification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_System__c</fullName>
        <globalPicklist>CRM_New</globalPicklist>
        <inlineHelpText>Choice the prospects current CRM system, can select several.</inlineHelpText>
        <label>CRM</label>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_End__c</fullName>
        <label>Fiscal Year End</label>
        <picklist>
            <picklistValues>
                <fullName>Jan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jul</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aug</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nov</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dec</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HR_System__c</fullName>
        <globalPicklist>HR_New</globalPicklist>
        <inlineHelpText>HR System</inlineHelpText>
        <label>HR</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MDF_Approval_Number__c</fullName>
        <label>MDF Approval Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDF_Sourced_Lead__c</fullName>
        <label>MDF Sourced Lead</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Partner Contact who submitted this Lead.</inlineHelpText>
        <label>Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Referal_Follow_Up__c</fullName>
        <description>Designates who will follow up with this partner referral</description>
        <inlineHelpText>Indicates who will follow up with this partner referral</inlineHelpText>
        <label>Follow up</label>
        <picklist>
            <picklistValues>
                <fullName>Adaptive Insights</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time_Frame__c</fullName>
        <label>Time Frame</label>
        <picklist>
            <picklistValues>
                <fullName>1 - 3 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - 6 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 - 12 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13 - 24 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Time Frame</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/LeadConvertController_Test.cls
/**@@
#APEX CLASS NAME       :   LeadConvertController_Test
#DESCRIPTION           :   This is test class for LeadConvertController Apex class.
@@**/
@isTest
public class LeadConvertController_Test {
    
    Static List<Account> accList;
    Static List<Lead> lstLead;
    Static List<Contact> lstCon;
    Static List<User> lstUser;
    
    /**@@
    #DESCRIPTION     : Creating test records
    #Paramaters      : None
    @@**/
    @testSetup static void setup() {
        
        
        List<User> ListUser = DataFactory.insertRunAsUser();
        
        System.runAs(ListUser[0]) {
            //DataFactory.insertCustomSetting();
        
        // Create Test Lead records
        lstLead = DataFactory.createLeadTestRecords('Test', 5);       
        
        //Insert acount
        accList = DataFactory.createAccountTestRecords('testaccountcompany',2);
        
        lstCon = DataFactory.createContactTestRecords('Test', accList[1].id, 1);
        //accList[0].Partner_Contact__c = lstCon[0].id;
        Profile portalProfile = [SELECT Id FROM Profile where Name=:'Partner Community User - Partner'];
        
        lstUser = DataFactory.insertPortalUser(lstCon[0].id);
        lstUser[0].ProfileId = portalProfile.Id;
        update lstUser;
      
        }
    }
    /**@@
    #DESCRIPTION     : This testMethod covers all the methods of LeadConvertController Apex class.
    #Paramaters      : None
    @@**/
    @isTest
    static void testMethodData() {
        
        user partnerUserObj = [Select id from user where profile.Name = 'Partner Community User - Partner' LIMIT 1];
        
        LeadConvertController.InitFieldsResponse lc = new LeadConvertController.InitFieldsResponse();
        
        lc = LeadConvertController.initFields();
        
       List<Lead> leadList = [Select id from lead limit 2];
       leadList[0].ownerId = partnerUserObj.id;
       leadList[1].ownerId = partnerUserObj.id;
       leadList[1].MDF_Sourced_Lead__c = 'Yes';
       leadList[1].Partner_Referal_Follow_Up__c = 'Partner';
       leadList[0].MDF_Sourced_Lead__c = 'Yes';
       leadList[0].Partner_Referal_Follow_Up__c = 'Partner';
       update leadList;
        
        //Get the test Account records by using a SOQL query
        List<Account> accObjList = [SELECT Id FROM Account LIMIT 2];
        accObjList[0].ownerId = partnerUserObj.id;
        //accObjList[1].ownerId = partnerUserObj.id;
        update accObjList;
        
        //LeadConvertController lcObj =new LeadConvertController();
        lead ld =LeadConvertController.fetchLeadDetail(leadList[0].id);
        
        Account acc =LeadConvertController.getAccount(accObjList[0].id);
        
        
        opportunity opp = new opportunity(Type = 'New',CloseDate = system.today() ,
                                          Likely__c= 123,ERP_System__c='Test ERP',HR_System__c='Test HR',
                                          CRM_System__c='Test CRM',Fiscal_Year_End__c = 'Jan',Budgeted_Project__c='Yes',
                                          Time_Frame__c= '1 -3 Months',Reason_for_change_Pain_Points__c='',MDF_Sourced_Lead__c='Yes',
                                          MDF_Approval_Number__c='12345',Referral_Follow_Up__c='Partner',
                                          Solution_Requirements__c = 'Dashboards', NextStep ='Test Next Step');
        
        boolean idp = LeadConvertController.ConvertLeadAction(True, True, opp, accObjList[0], leadList[0].id);
        boolean idp1 = LeadConvertController.ConvertLeadAction(True, false, opp, accObjList[1], leadList[1].id);
         
        
        }
}