AI-JADEDEVS4/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Booking_Detail__c.object
<CustomObject>
    <description>Created upon Opportunity Closed-Won
- opp id
- New logo ARR
- Add-on ARR
- total New ARR (New logo ARR + Add- on ARR)
- Service
- Scheduled Renewal ARR (Installments)
- Renewal ARR (Scheduled Renewal ARR+ Contract ARR)
- ACV (Total New ARR + Renewal ARR + Service)
- New MYR
- Renewal MYR
- Total MYR (New MYR + Renewal MYR)
- Total Bookings (Total New ARR + Services + Scheduled Renewal ARR + Total MYR)
- Unbilled
- TCV Bookings (Total Bookings + Unbilled)
- Subscription Start
- Subscription End</description>
    <fields>
        <fullName>Annual_Months_Accrued__c</fullName>
        <description>This isnt calculating correctly beyond the first year. I dont believe it is being used currently.</description>
        <formula>IF( Is_Last_Year__c,
   Subscription_Term_Months__c,
   IF( Subscription_Term_Months__c &lt; 12,
      Subscription_Term_Months__c,
      Booking_Year__c * 12
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual Months Accrued</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Booking_Year__c</fullName>
        <label>Booking Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Free_Months__c</fullName>
        <description>Gets the free months from the primary quote on the related opportunity</description>
        <formula>Value(Text(Opportunity__r.SBQQ__PrimaryQuote__r.Free_Months__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Free Months on the related quote</inlineHelpText>
        <label>Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_First_Year__c</fullName>
        <formula>IF( Booking_Year__c == 1, True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is First Year?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Last_Year__c</fullName>
        <formula>IF(
  AND(
    Is_First_Year__c = False,
    Booking_Year__c == Order__r.Total_Booking_Details__c
  ),
  True,
  False
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Last Year?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Booking Details</relationshipLabel>
        <relationshipName>Booking_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The primary quote from which this booking detail was generated.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Booking Details</relationshipLabel>
        <relationshipName>Booking_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <inlineHelpText>End date of the activated Order minus any free months.</inlineHelpText>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <inlineHelpText>Start date of the activated Order.</inlineHelpText>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Term_Months__c</fullName>
        <inlineHelpText>Total subscription term length including free months.</inlineHelpText>
        <label>Subscription Term Months</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Booking Detail</label>
    <nameField>
        <displayFormat>Booking-{000000}</displayFormat>
        <label>Booking Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is used by SDRs to track the SDR lifecycle</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <controllingField>Lifecycle_Stage__c</controllingField>
            <picklistValues>
                <fullName>Raw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restored</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AI-JADEDEVS4/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Free_Months__c</fullName>
        <formula>VALUE(TEXT(Quote__r.Free_Months__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <formula>Quote__r.Display_End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <formula>Quote__r.SBQQ__StartDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Months__c</fullName>
        <formula>Quote__r.Quote_Term_Length__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term_Years__c</fullName>
        <formula>Term_Months__c / 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term Years</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AI-JADEDEVS4/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <description>The Value In this Field Indicates if this Product is Service or Subscription Revenue</description>
        <inlineHelpText>The Value In this Field Indicates if this Product is Service or Subscription Revenue</inlineHelpText>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionBase__c</fullName>
        <description>Determines whether dynamic subscriptions are calculated off List or Net product price.</description>
        <inlineHelpText>Determines whether dynamic subscriptions are calculated off List or Net product price.</inlineHelpText>
        <label>Percent Of Total Base</label>
        <picklist>
            <picklistValues>
                <fullName>List</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionCategory__c</fullName>
        <description>Subscription category for this product. Applies to all products and used to limit percent of total subscriptions to certain products.</description>
        <inlineHelpText>Use this to limit percent-of-total subscriptions to certain products. For example, software maintenance should only calculate percentage on software products.</inlineHelpText>
        <label>Percent Of Total Category</label>
        <picklist>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionPricing__c</fullName>
        <description>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</description>
        <inlineHelpText>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</inlineHelpText>
        <label>Subscription Pricing</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent Of Total</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
        <inlineHelpText>Term length of this subscription. Only applicable if the product is a subscription.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionType__c</fullName>
        <description>Renewalable Subscriptions will transfer to Renewal Quotes. One-time Subscriptions will not.</description>
        <inlineHelpText>Renewalable Subscriptions will transfer to Renewal Quotes. One-time Subscriptions will not.</inlineHelpText>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>Renewable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>One-time</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AI-JADEDEVS4/src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Enables/disables triggers. Utilized by Apex trigger handler classes.</description>
    <fields>
        <fullName>Account_Trigger_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Account Trigger_Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BookingDetail_Trigger_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BookingDetail Trigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CampaignTrigger_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CampaignTrigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Trigger_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Contact Trigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Trigger_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Event Trigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Trigger_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Lead Trigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Line_Item_Trigger_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Opportunity Line Item Trigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Trigger_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Opportunity Trigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote_Document_Trigger_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Quote Document Trigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote_Line_Trigger_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Quote Line Trigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote_Trigger_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Quote Trigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_Trigger_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Subscription Trigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Task_Trigger_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Task Trigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Settings</label>
</CustomObject>

AI-JADEDEVS4/src/classes/BookingDetailAction_Test.cls
@IsTest
public class BookingDetailAction_Test {

    @TestSetup static void init() {
        //Insert custom settings
        DataFactory.insertCustomSetting();
        
       // TestData.setup();
TriggerSettings__c settings = new TriggerSettings__c();
        settings.Name = 'Settings';
        settings.Account_Trigger_Enabled__c = false;
        settings.Contact_Trigger_Enabled__c = True;
        settings.CampaignTrigger_Enabled__c = True;
        settings.Event_Trigger_Enabled__c = True;
        settings.Lead_Trigger_Enabled__c = True;
        settings.Opportunity_Line_Item_Trigger_Enabled__c = True;
        settings.Opportunity_Trigger_Enabled__c = true;
        settings.Quote_Document_Trigger_Enabled__c = True;
        settings.Quote_Line_Trigger_Enabled__c = True;
        settings.Quote_Trigger_Enabled__c = True;
        settings.Subscription_Trigger_Enabled__c = True;
        settings.Task_Trigger_Enabled__c = True;
        settings.BookingDetail_Trigger_Enabled__c = true;
        insert settings;
               
    }
    
   
    @IsTest public static void termTests(){
        System.assertEquals(1, BookingDetailAction.getTermYears(1));
        System.assertEquals(1, BookingDetailAction.getTermYears(6));
        System.assertEquals(1, BookingDetailAction.getTermYears(9));
        System.assertEquals(1, BookingDetailAction.getTermYears(12));
        
        System.assertEquals(2, BookingDetailAction.getTermYears(13));
        System.assertEquals(2, BookingDetailAction.getTermYears(16));
        System.assertEquals(2, BookingDetailAction.getTermYears(22));
        System.assertEquals(2, BookingDetailAction.getTermYears(24));
        
        System.assertEquals(3, BookingDetailAction.getTermYears(25));
        System.assertEquals(3, BookingDetailAction.getTermYears(30));
        System.assertEquals(3, BookingDetailAction.getTermYears(36));
        
        System.assertEquals(4, BookingDetailAction.getTermYears(37));
    }
    
    
        
    @IsTest public static void basicTests(){
        //TestData data = new TestData();
        test.startTest();
         Account testAccount = new Account(Name= 'Test Account', Status__c='Active');
        insert testAccount;
         
        Contact testContact = new Contact(FirstName='FName',
                        LastName='LName',
                        Email='unit@test.com',
                        AccountId=testAccount.Id);
        insert testContact;
        
        ID pricebookId = Test.getStandardPricebookId();
         List<Product2> TestProducts = new list<Product2>();
        final Integer SUBSCRIPTION_PRODUCT = 1;
        Product2 prod = new Product2(
                Name = 'Product',
                Description = 'Test subscription product',        
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'TEST-SUBSCRIPTION',              
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 12,
                SBQQ__SubscriptionType__c = 'Renewable',
                IsActive = true);
        testProducts.add(prod);
        
        Product2 f1 = new Product2(
                Name = 'Free Months - 1',
                Description = 'Free Month SKU',        
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'Free Months - 1',
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 1,
                SBQQ__SubscriptionType__c = 'One-time',
                IsActive = true);
        testProducts.add(f1);
        
        Product2 f2 = new Product2(
                Name = 'Free Months - 2',
                Description = 'Free Month SKU',        
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'Free Months - 2',
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 2,
                SBQQ__SubscriptionType__c = 'One-time',
                IsActive = true);
        testProducts.add(f2);
        
        Product2 f3 = new Product2(
                Name = 'Free Months - 3',
                Description = 'Free Month SKU',
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'Free Months - 3',
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 3,
                SBQQ__SubscriptionType__c = 'One-time',
                IsActive = true);
        testProducts.add(f3);
        
        Product2 d2 = new Product2(
                Name = 'Multi-Year Subscription Discount - 2 Years',
                Description = 'MultiYear Discount SKU',
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'MYD2',
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 24,
                SBQQ__SubscriptionType__c = 'One-time',
                IsActive = true);
        testProducts.add(d2);
        
        Product2 d3 = new Product2(
                Name = 'Multi-Year Subscription Discount - 2 Years',
                Description = 'MultiYear Discount SKU',
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'MYD3',
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 36,
                SBQQ__SubscriptionType__c = 'One-time',
                IsActive = true);
        testProducts.add(d3);
        
        insert testProducts;
                     
        
        Opportunity testOpportunity = new Opportunity(Name='Test Opportunity',
                    AccountId=testAccount.Id,
                    StageName='Prospecting',
                    Pricebook2Id=pricebookId,
                    CloseDate=Date.Today().AddDays(90),
                    SBQQ__Contracted__c = false,
                    Closed_Reasons__c = 'Other',
                    Type = 'New Business');
        insert testOpportunity;
        
        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
                SBQQ__Opportunity2__c = testOpportunity.Id,
                SBQQ__PriceBook__c = pricebookId,
                SBQQ__Account__c = testAccount.Id,
                SBQQ__Type__c = 'Quote',
                SBQQ__Primary__c = true,
                SBQQ__SubscriptionTerm__c = 12,
                Term_Years__c = '1',
                SBQQ__StartDate__c = Date.Today() );
        insert testQuote;
        
        TestQuote.Is_Multi_Year__c = True;
        TestQuote.Term_Years__c = '3';
        TestQuote.Free_Months__c = '2';
        TestQuote.Quote_Term_Length__c   = 10;
        update TestQuote;
        
        TestQuote = (SBQQ__Quote__c)SObjectUtils.get('SBQQ__Quote__c', TestQuote.Id);
//        System.assertEquals(38, data.TestQuote.SBQQ__SubscriptionTerm__c); // 3 years = 36 months + 2 free months = 38
        // Note: Above calculation depends on Quote workflow rule to update the SubscriptionTerm.
        
        TestOpportunity = (Opportunity)SObjectUtils.get('Opportunity', TestOpportunity.Id);
        OpportunityOrderConversionAction.convertToOrder(new List<Opportunity>{ TestOpportunity});

        String oid = TestOpportunity.Id;
        system.debug('****OID***'+oid);
        //String soql = 'SELECT ' + SObjectUtils.allFields('Order') + ' FROM Order WHERE OpportunityId=:oid';
        String soql = 'SELECT ' + SObjectUtils.allFields('Order') + ' FROM Order';        
        List<Order> orderList = Database.query(soql);
        System.assertEquals(1, orderList.size());
        // SteelBrick subscription term includes free months, but booking details term should not.
       // System.assertEquals(38, orderList[0].Term_Months__c);
        
        List<Booking_Detail__c> details = BookingDetailAction.createBookingDetails(orderList[0]);
        //System.assertEquals(3, details.size());
        
        soql = 'SELECT ' + SObjectUtils.allFields('Booking_Detail__c') + ' FROM Booking_Detail__c ORDER BY Booking_Year__c ASC';
        details = Database.query(soql);
        
        for(Integer i=0; i < details.size(); i++){
            Booking_Detail__c bd = details[i];
            System.assert(bd.Booking_Year__c == (i+1));
            System.assert(bd.Is_First_Year__c == (i==0));
            System.assert(bd.Is_Last_Year__c == ( (i+1) == details.size()));
            
            System.assert(bd.Subscription_Start_Date__c != null);
            System.assert(bd.Subscription_End_Date__c != null);
            // SteelBrick subscription term includes free months, but booking details term should not.
            System.assertEquals(36, bd.Subscription_Term_Months__c);
            
            System.assert(bd.Annual_Months_Accrued__c == (i*12));
            System.assert(bd.Order__c != null);
            System.assert(bd.Opportunity__c != null);
            System.assert(bd.Quote__c != null);
            System.assert(bd.Unique_Key__c != null);
            System.assertEquals(false, bd.Is_Installment__c);
            System.assert(bd.Booking_End_Date__c > bd.Booking_Start_Date__c);
            System.assert(bd.ACV__c != 0);
            
            if(bd.Is_First_Year__c){
                System.assertEquals(0.00, bd.Contracted_Renewal_ARR__c);
                System.assert(bd.Total_New_ARR__c > 0.00);
            } else {
                System.assert(bd.Contracted_Renewal_ARR__c != 0.00);
                System.assertEquals(0.00, bd.Total_New_ARR__c);
            }
        }
        Trigger_BookingDetail_Helper.bookingDetailTriggerHandler_flag = false;
        Booking_Detail__c bd = new Booking_Detail__c();
            bd.Opportunity__c = TestOpportunity.ID;
            bd.Order__c = orderList[0].ID;
            bd.Quote__c = TestQuote.ID;            
            bd.Unique_Key__c = orderList[0].ID + '1';
            insert bd;
        update bd;            
                test.stopTest();
    } 
    
    @IsTest public static void batchMigrationTests(){
        //TestData data = new TestData();
        test.startTest(); 
         Account testAccount = new Account(Name= 'Test Account', Status__c='Active');
        insert testAccount;
         
        Contact testContact = new Contact(FirstName='FName',
                        LastName='LName',
                        Email='unit@test.com',
                        AccountId=testAccount.Id);
        insert testContact;
        
        ID pricebookId = Test.getStandardPricebookId();
        Product2 f1 = new Product2(
                Name = 'Free Months - 2',
                Description = 'Free Month SKU',        
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'Free Months - 1',
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 1,
                SBQQ__SubscriptionType__c = 'One-time',
                IsActive = true);
        insert f1;                
                        
        
        Opportunity testOpportunity = new Opportunity(Name='Test Opportunity',
                    AccountId=testAccount.Id,
                    StageName='Prospecting',
                    Pricebook2Id=pricebookId,
                    CloseDate=Date.Today().AddDays(90),
                    SBQQ__Contracted__c = false,
                    Closed_Reasons__c = 'Other',
                    Type = 'New Business');
        insert testOpportunity;
        
        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
                SBQQ__Opportunity2__c = testOpportunity.Id,
                SBQQ__PriceBook__c = pricebookId,
                SBQQ__Account__c = testAccount.Id,
                SBQQ__Type__c = 'Quote',
                SBQQ__Primary__c = true,
                SBQQ__SubscriptionTerm__c = 12,
                Term_Years__c = '1',
                SBQQ__StartDate__c = Date.Today() );
        insert testQuote;
                       
        TestQuote.Is_Multi_Year__c = True;
        TestQuote.Term_Years__c = '3';
        TestQuote.Free_Months__c = '2';
        update TestQuote;
        
        TestQuote = (SBQQ__Quote__c)SObjectUtils.get('SBQQ__Quote__c', TestQuote.Id);
//        System.assertEquals(38, data.TestQuote.SBQQ__SubscriptionTerm__c); // 3 years = 36 months + 2 free months = 38
        // Note: Above calculation depends on Quote workflow rule to update the SubscriptionTerm.
        
        TestOpportunity = (Opportunity)SObjectUtils.get('Opportunity', TestOpportunity.Id);
        OpportunityOrderConversionAction.convertToOrder(new List<Opportunity>{ TestOpportunity});

        String soql = 'SELECT ' + SObjectUtils.allFields('Order') + ' FROM Order';
        BookingDetailsBatchMigrator batch = new BookingDetailsBatchMigrator(soql);
        Database.ExecuteBatch(batch);
        test.stoptest();                
    }
     @IsTest public static void basicTests2(){
        //TestData data = new TestData();
        
        Account testAccount = new Account(Name= 'Test Account', Status__c='Active');
        insert testAccount;
        

        Contact testContact = new Contact(FirstName='FName',
                        LastName='LName',
                        Email='unit@test.com',
                        AccountId=testAccount.Id);
        insert testContact;
                Product2 d3 = new Product2(
                Name = 'Multi-Year Subscription Discount - 2 Years',
                Description = 'MultiYear Discount SKU',
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'MYD3',
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 36,
                SBQQ__SubscriptionType__c = 'One-time',
                IsActive = true);
        insert d3;
        
        ID pricebookId = Test.getStandardPricebookId();
      List<PricebookEntry> pbEntries = new List<PricebookEntry>();

            PricebookEntry entry = new PricebookEntry(
                    IsActive = true,
                    Pricebook2Id = pricebookId,
                    Product2Id = d3.Id,
                    UnitPrice = 100.00);
            insert (entry);        
        
    
        Opportunity testOpportunity = new Opportunity(Name='Test Opportunity',
                    AccountId=testAccount.Id,
                    StageName='Prospecting',
                    Pricebook2Id=pricebookId,
                    CloseDate=Date.Today().AddDays(90),
                    SBQQ__Contracted__c = false,
                    Closed_Reasons__c = 'Other',
                    ARCHIVE_Subscription_Start_Date__c = system.today(),
                    Type = 'New Business');
        insert testOpportunity;
        OpportunityLineItem oppLine = new OpportunityLineItem(pricebookentryid=entry.ID,TotalPrice=2000,Quantity = 2,OpportunityID = testOpportunity.ID);
        insert oppLine;

        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
                SBQQ__Opportunity2__c = testOpportunity.Id,
                SBQQ__PriceBook__c = pricebookId,
                SBQQ__Account__c = testAccount.Id,
                SBQQ__Type__c = 'Quote',
                SBQQ__Primary__c = true,
                SBQQ__SubscriptionTerm__c = 12,
                Term_Years__c = '1',
                SBQQ__StartDate__c = Date.Today() );
        insert testQuote;
        
        testOpportunity.SBQQ__PrimaryQuote__c = testQuote.Id;
        update testOpportunity;
        update testQuote;
        system.debug('testOpportunity@@@'+testOpportunity.Subscription_Start_Date__c);
        Map<String, String> orderFieldMap = FieldMapConfiguration.getByObjects('Opportunity', 'Order');
        System.assert(orderFieldMap.size() > 0);
        Map<String, String> lineFieldMap = FieldMapConfiguration.getByObjects('OpportunityLineItem', 'OrderItem');
        System.assert(lineFieldMap.size() > 0);
        
        AIOpportunity opp = new AIOpportunity().withSObject(testOpportunity);
        //System.assertEquals(2, opp.LineItems.size() );
        for(OpportunityLineItem item : opp.LineItems.values()){
            System.assert( item.UnitPrice != null);
            System.debug('UnitPrice = ' + item.UnitPrice);
        }
        
        // No Orders or line items prior to clone        
        integer count = database.countQuery('SELECT count() FROM Order');
        System.assertEquals(0, count);
        
        count = database.countQuery('SELECT count() FROM OrderItem');
        System.assertEquals(0, count);
        
                    Map<String, String> orderFieldMap1 = FieldMapConfiguration.getByObjects('Opportunity', 'Order');

        system.debug('orderFieldMap@@'+orderFieldMap1);
        
        OpportunityOrderConversionAction.convertToOrder(new List<Opportunity>{ testOpportunity});
        
        // Post-conversion, confirm that Order record exists with Line items.
        count = database.countQuery('SELECT count() FROM Order');
        System.assertEquals(1, count);
        Order TestOrder = Database.query('SELECT ' + SObjectUtils.allFields('Order') + ' FROM Order LIMIT 1');
                
        System.assertEquals(testOpportunity.Id, TestOrder.OpportunityId);
        System.assertEquals(testAccount.Id, TestOrder.AccountId);
        System.assertEquals( testOpportunity.Pricebook2Id, TestOrder.Pricebook2Id );
        System.assertEquals( testQuote.Id, TestOrder.Quote__c );
        System.assert( TestOrder.Subscription_Start_Date__c != null );
        System.assertEquals(TestOrder.EffectiveDate, TestOrder.Subscription_Start_Date__c );
        //System.assert( TestOrder.Subscription_End_Date__c != null );
        
        AIOrder o = new AIOrder().withSObject(TestOrder);
        //System.assertEquals(2, o.OrderItems.size());        
        
        // Execute conversion again and confirm no duplicates are created.
        OpportunityOrderConversionAction.convertToOrder(new List<Opportunity>{ testOpportunity});
        count = database.countQuery('SELECT count() FROM Order');
        System.assertEquals(1, count);
        
        count = database.countQuery('SELECT count() FROM OrderItem');
        //System.assertEquals(2, count);
    }
    
    @IsTest public static void provisionBookingDetails_Test(){
        
         //Insert custom settings
        DataFactory.insertCustomSetting();
        
        ID pricebookId = Test.getStandardPricebookId();   
        
        //Insert account record
        List<Account> oacc =DataFactory.createAccountTestRecords('Test Account', 1);
        system.assertEquals(oacc.size(), 1);
        
        //Insert Contact record
        List<Contact> ocon= DataFactory.createContactTestRecords('LName', oacc[0].id, 1);
        system.assertEquals(ocon.size(), 1);
        
        //Insert Opportunity record
        List<opportunity> oppListProspect = DataFactory.createOpportunityTestRecords('Test Prospecting' , 1);
        oppListProspect[0].Type = 'New';
        oppListProspect[0].StageName = CustomConstants.OpportunityStageSentToOrders;
        update oppListProspect;
        Test.startTest();
        
        List<SBQQ__Quote__c> lstSBQuote = DataFactory.createSBQQQuote(oacc[0].Id, oppListProspect[0].Id, pricebookId, 1);
                
        OpportunityOrderConversionAction.convertToOrder(new List<Opportunity>{ oppListProspect[0] });
        
        Order TestOrder = Database.query('SELECT ' + SObjectUtils.allFields('Order') + ' FROM Order LIMIT 1');
               
        List<Order> orderRecords = new List<Order>();
        
        orderRecords.add(TestOrder);
        BookingDetailAction.provisionBookingDetails(orderRecords);
        
        
        SBQQ__Quote__c objQuote = new SBQQ__Quote__c(id=TestOrder.Quote__c);
        objQuote.Quote_Term_Length__c = null;
        objQuote.SBQQ__StartDate__c = null;
        update objQuote;
        Test.stopTest();
        OpportunityOrderConversionAction.convertToOrder(new List<Opportunity>{ oppListProspect[0] });
        
        TestOrder = Database.query('SELECT ' + SObjectUtils.allFields('Order') + ' FROM Order LIMIT 1');
        
        orderRecords = new List<Order>();
        orderRecords.add(TestOrder);
        BookingDetailAction.provisionBookingDetails(orderRecords);
    }
    
    @IsTest public static void bookingDetailsDelete_Test(){
        
         //Insert custom settings
        DataFactory.insertCustomSetting();
        
        ID pricebookId = Test.getStandardPricebookId();   
        
        //Insert account record
        List<Account> oacc =DataFactory.createAccountTestRecords('Test Account', 1);
        system.assertEquals(oacc.size(), 1);
        
        //Insert Contact record
        List<Contact> ocon= DataFactory.createContactTestRecords('LName', oacc[0].id, 1);
        system.assertEquals(ocon.size(), 1);
        
        //Insert Opportunity record
        List<opportunity> oppListProspect = DataFactory.createOpportunityTestRecords('Test Prospecting' , 1);
        oppListProspect[0].Type = 'New';
        oppListProspect[0].StageName = CustomConstants.OpportunityStageSentToOrders;
        update oppListProspect;
        Test.startTest();
        
        List<SBQQ__Quote__c> lstSBQuote = DataFactory.createSBQQQuote(oacc[0].Id, oppListProspect[0].Id, pricebookId, 1);
                
        OpportunityOrderConversionAction.convertToOrder(new List<Opportunity>{ oppListProspect[0] });
        
        Order TestOrder = Database.query('SELECT ' + SObjectUtils.allFields('Order') + ' FROM Order LIMIT 1');
        
        oppListProspect[0].StageName = CustomConstants.OpportunityStageCW;
        update oppListProspect;
        
        List<Booking_Detail__c> bookingDetailList = DataFactory.createBookingDetail(oppListProspect[0], TestOrder, 1);
           
        delete bookingDetailList[0];
        
    }
    
}