AI-JADEDEVS4/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is used by SDRs to track the SDR lifecycle</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <controllingField>Lifecycle_Stage__c</controllingField>
            <picklistValues>
                <fullName>Raw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restored</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unqualified_Reason__c</fullName>
        <label>Unqualified Reason</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Solution Not A Fit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Is A Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer With Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Feature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-responsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not the right size</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No CPM background</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud CPM Competitor practice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No GTM alignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Products not complementary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lack of Executive Support</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Enables/disables triggers. Utilized by Apex trigger handler classes.</description>
    <fields>
        <fullName>CampaignTrigger_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CampaignTrigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Settings</label>
</CustomObject>

AI-JADEDEVS4/src/classes/CampaignMemberTrigger_Test.cls
@IsTest
public class CampaignMemberTrigger_Test
{       
    @IsTest 
     public static void Test1(){
     Test.startTest();
        Account testAccount = new Account(Name= 'Test Account', Status__c='Active');
        insert testAccount;
         
        Contact testContact = new Contact(FirstName='FName',
                        LastName='LName',
                        Email='unit@test.com',
                        AccountId=testAccount.Id);
        insert testContact;
        
        Insert new TriggerSettings__c(Name = 'Settings', CampaignTrigger_Enabled__c = TRUE);
        
        Campaign testCampaign = new Campaign(Name='Test Campaign');
        insert testCampaign;
        
      //Creates a new campaign memeber, associaites it with 1 provider sales campaign, and inserts
          contact oCon = new Contact(ID=testContact.ID,Status__c='Unqualified',Unqualified_Reason__c='Your are Unqualified');
        update oCon;  
        CampaignMember newMember = 
        new CampaignMember(CampaignID =TestCampaign.ID, ContactID = oCon.ID);
        insert newMember; 
        
        Test.stopTest();               
                                     
     }
     
}