AI-JADEDEVS4/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Cancelled</fullName>
        <active>true</active>
        <label>Cancelled</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status(Archived)</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NLWC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engaged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is used by SDRs to track the SDR lifecycle</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <controllingField>Lifecycle_Stage__c</controllingField>
            <picklistValues>
                <fullName>Raw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restored</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/AccountCancelController.cls
public class AccountCancelController {
    public Account currentAccount {get; set;}
    public ID currentID {get; set;}

    public AccountCancelController(ApexPages.StandardController standardController) 
    {
        currentID = ApexPages.currentPage().getParameters().get('id');
        currentAccount = (Account)SObjectUtils.get('Account', currentID);
    }
    
    public PageReference cancelAccount(){        
        closeOpportunities(currentID);
        cancelContacts(currentID);
        currentAccount.Status__c = 'Cancelled';
        update currentAccount;
        return new PageReference('/'+currentAccount.Id);
    }
    
    public Integer closeOpportunities(ID aid){
        List<Opportunity> openOpps = [SELECT Id, IsClosed,StageName,Loss_Reason__c FROM Opportunity WHERE AccountId=:aid AND IsClosed=False];
        for(Opportunity oppty : openOpps){
            oppty.StageName = 'Closed Lost';
            oppty.Loss_Reason__c = 'Cancelled';
        }
        update openOpps;
        return openOpps.size();
    }
    
    public Integer cancelContacts(ID aid){
        List<Contact> accountContacts = [SELECT Id, AccountId, Status__c FROM Contact WHERE AccountId=:aid];
        for(Contact c : accountContacts){
            c.Contact_Status__c = 'Cancelled';
        }
        update accountContacts;
        return accountContacts.size();
    }
}