AI-JADEDEVS4/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Special_Terms__c</fullName>
        <label>Special Terms</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is used by SDRs to track the SDR lifecycle</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <controllingField>Lifecycle_Stage__c</controllingField>
            <picklistValues>
                <fullName>Raw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restored</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AI-JADEDEVS4/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Special_Terms__c</fullName>
        <label>Special Terms</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <formula>Quote__r.Display_End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <formula>Quote__r.SBQQ__StartDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Years__c</fullName>
        <formula>Term_Months__c / 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term Years</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AI-JADEDEVS4/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <description>The Value In this Field Indicates if this Product is Service or Subscription Revenue</description>
        <inlineHelpText>The Value In this Field Indicates if this Product is Service or Subscription Revenue</inlineHelpText>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionBase__c</fullName>
        <description>Determines whether dynamic subscriptions are calculated off List or Net product price.</description>
        <inlineHelpText>Determines whether dynamic subscriptions are calculated off List or Net product price.</inlineHelpText>
        <label>Percent Of Total Base</label>
        <picklist>
            <picklistValues>
                <fullName>List</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionCategory__c</fullName>
        <description>Subscription category for this product. Applies to all products and used to limit percent of total subscriptions to certain products.</description>
        <inlineHelpText>Use this to limit percent-of-total subscriptions to certain products. For example, software maintenance should only calculate percentage on software products.</inlineHelpText>
        <label>Percent Of Total Category</label>
        <picklist>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionPricing__c</fullName>
        <description>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</description>
        <inlineHelpText>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</inlineHelpText>
        <label>Subscription Pricing</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent Of Total</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
        <inlineHelpText>Term length of this subscription. Only applicable if the product is a subscription.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionType__c</fullName>
        <description>Renewalable Subscriptions will transfer to Renewal Quotes. One-time Subscriptions will not.</description>
        <inlineHelpText>Renewalable Subscriptions will transfer to Renewal Quotes. One-time Subscriptions will not.</inlineHelpText>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>Renewable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>One-time</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AI-JADEDEVS4/src/classes/OpportunityOrderConversionAction_Tests.cls
/**@@
#CLASS NAME                :    OpportunityOrderConversionAction_Tests
#DESCRIPTION                   :   Test class for "OpportunityOrderConversionAction"  
@@**/

@IsTest
public class OpportunityOrderConversionAction_Tests {

    @TestSetup static void init() {
        //TestData.setup();
    }
    
    @IsTest public static void basicTests(){
        //TestData data = new TestData();
        
        Account testAccount = new Account(Name= 'Test Account', Status__c='Active');
        insert testAccount;
        

        Contact testContact = new Contact(FirstName='FName',
                        LastName='LName',
                        Email='unit@test.com',
                        AccountId=testAccount.Id);
        insert testContact;
                Product2 d3 = new Product2(
                Name = 'Multi-Year Subscription Discount - 2 Years',
                Description = 'MultiYear Discount SKU',
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'MYD3',
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 36,
                SBQQ__SubscriptionType__c = 'One-time',
                IsActive = true);
        insert d3;
        
        ID pricebookId = Test.getStandardPricebookId();
      List<PricebookEntry> pbEntries = new List<PricebookEntry>();

            PricebookEntry entry = new PricebookEntry(
                    IsActive = true,
                    Pricebook2Id = pricebookId,
                    Product2Id = d3.Id,
                    UnitPrice = 100.00);
            insert (entry);        
        
    
        Opportunity testOpportunity = new Opportunity(Name='Test Opportunity',
                    AccountId=testAccount.Id,
                    StageName='Prospecting',
                    Pricebook2Id=pricebookId,
                    CloseDate=Date.Today().AddDays(90),
                    SBQQ__Contracted__c = false,
                    Closed_Reasons__c = 'Other',
                    ARCHIVE_Subscription_Start_Date__c = system.today(),
                    Type = 'New Business');
        insert testOpportunity;
        OpportunityLineItem oppLine = new OpportunityLineItem(pricebookentryid=entry.ID,TotalPrice=2000,Quantity = 2,OpportunityID = testOpportunity.ID);
        insert oppLine;

        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
                SBQQ__Opportunity2__c = testOpportunity.Id,
                SBQQ__PriceBook__c = pricebookId,
                SBQQ__Account__c = testAccount.Id,
                SBQQ__Type__c = 'Quote',
                SBQQ__Primary__c = true,
                SBQQ__SubscriptionTerm__c = 12,
                Term_Years__c = '1',
                SBQQ__StartDate__c = Date.Today() );
        insert testQuote;
        
        testOpportunity.SBQQ__PrimaryQuote__c = testQuote.Id;
        update testOpportunity;
        update testQuote;
        system.debug('testOpportunity@@@'+testOpportunity.Subscription_Start_Date__c);
        Map<String, String> orderFieldMap = FieldMapConfiguration.getByObjects('Opportunity', 'Order');
        System.assert(orderFieldMap.size() > 0);
        Map<String, String> lineFieldMap = FieldMapConfiguration.getByObjects('OpportunityLineItem', 'OrderItem');
        System.assert(lineFieldMap.size() > 0);
        
        AIOpportunity opp = new AIOpportunity().withSObject(testOpportunity);
        //System.assertEquals(2, opp.LineItems.size() );
        for(OpportunityLineItem item : opp.LineItems.values()){
            System.assert( item.UnitPrice != null);
            System.debug('UnitPrice = ' + item.UnitPrice);
        }
        
        // No Orders or line items prior to clone        
        integer count = database.countQuery('SELECT count() FROM Order');
        System.assertEquals(0, count);
        
        count = database.countQuery('SELECT count() FROM OrderItem');
        System.assertEquals(0, count);
        
                    Map<String, String> orderFieldMap1 = FieldMapConfiguration.getByObjects('Opportunity', 'Order');

        system.debug('orderFieldMap@@'+orderFieldMap1);
        
        OpportunityOrderConversionAction.convertToOrder(new List<Opportunity>{ testOpportunity});
        
        // Post-conversion, confirm that Order record exists with Line items.
        count = database.countQuery('SELECT count() FROM Order');
        System.assertEquals(1, count);
        Order TestOrder = Database.query('SELECT ' + SObjectUtils.allFields('Order') + ' FROM Order LIMIT 1');
        System.assertEquals(testOpportunity.Id, TestOrder.OpportunityId);
        System.assertEquals(testAccount.Id, TestOrder.AccountId);
        System.assertEquals( testOpportunity.Pricebook2Id, TestOrder.Pricebook2Id );
        System.assertEquals( testQuote.Id, TestOrder.Quote__c );
        System.assert( TestOrder.Subscription_Start_Date__c != null );
        System.assertEquals(TestOrder.EffectiveDate, TestOrder.Subscription_Start_Date__c );
        //System.assert( TestOrder.Subscription_End_Date__c != null );
        
        AIOrder o = new AIOrder().withSObject(TestOrder);
        //System.assertEquals(2, o.OrderItems.size());        
        
        // Execute conversion again and confirm no duplicates are created.
        OpportunityOrderConversionAction.convertToOrder(new List<Opportunity>{ testOpportunity});
        count = database.countQuery('SELECT count() FROM Order');
        System.assertEquals(1, count);
        
        count = database.countQuery('SELECT count() FROM OrderItem');
        //System.assertEquals(2, count);
    }
     /**@@
        #TEST METHOD   : populateOppSpecialTermTest()
        #DESCRIPTION   : Populating the Internal Term from opportunity on Order creation
    @@**/
    public static testMethod void populateOppSpecialTermTest(){
    
        //Inserting custom setting
        DataFactory.insertCustomSetting();
        
        //Insert acount record
        List<Account> accList = DataFactory.createAccountTestRecords('TestAccount',1);
                
        //Insert contact record
        List<Contact> contactList = DataFactory.createContactTestRecords('ContactTest',accList[0].Id,1);
        
        List<Opportunity> oppList = DataFactory.createOpportunityTestRecords('TestOpportunity',1);
        
        List<Order> orderList = DataFactory.createOrderTestRecords('TestOrder', oppList[0].id, accList[0].id, 1);
        System.assertEquals(oppList[0].Special_Terms__c,'TestInternal Notes');
        
        delete orderList;
        undelete orderList;
     }//END OF METHOD   
     
     /**@@
        #TEST METHOD   : populateQuoteSpecialTermTest()
        #DESCRIPTION   : Populating the Special Term from Quote on Order creation
    @@**/
    public static testMethod void populateQuoteSpecialTermTest(){
    
        //Inserting custom setting
        DataFactory.insertCustomSetting();
        
        //Insert acount record
        List<Account> accList = DataFactory.createAccountTestRecords('TestAccount',1);
        
        //Insert contact record
        List<Contact> contactList = DataFactory.createContactTestRecords('ContactTest',accList[0].Id,1);
        
        List<Opportunity> oppList = DataFactory.createOpportunityTestRecords('TestOpportunity',1);
        
        List<SBQQ__Quote__c> quoteList = DataFactory.createQuoteTestRecords(oppList[0].id,1);
        
        List<Order> orderList = DataFactory.createOrderTestRecords('TestOrder', oppList[0].id, accList[0].id, 1);
        System.assertEquals(orderList[0].Special_Terms__c,'TestOrder');
        
        delete orderList;
        undelete orderList;
        
     }//END OF METHOD
}