AI-JADEDEVS4/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_CSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account CSM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT(Account.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calculated_Score__c</fullName>
        <description>This field score is calculated based on the MAX score between HubSpot&apos;s or Eloqua&apos;s Score, whichever is highest</description>
        <formula>MAX(HubSpot_Lead_Score__c,CASE(Eloqua_Lead_Score__c,&quot;A1&quot;,88,&quot;B1&quot;,85,&quot;C1&quot;,73,&quot;D1&quot;,71,&quot;A2&quot;,68,&quot;B2&quot;,65,&quot;C2&quot;,53,&quot;D2&quot;,50,&quot;A3&quot;,49,&quot;B3&quot;,47,&quot;C3&quot;,34,&quot;D3&quot;,30,&quot;A4&quot;,25,&quot;B4&quot;,22,&quot;C4&quot;,15,&quot;D4&quot;,10,0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field score is calculated based on the MAX score between HubSpot&apos;s or Eloqua&apos;s Score, whichever is highest</inlineHelpText>
        <label>Lead Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Offer_Most_Recent__c</fullName>
        <label>Lead Offer - Most Recent</label>
        <picklist>
            <picklistValues>
                <fullName>Adaptive Live 2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive myDials Contact Me Form - General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive myDials Contact Me Form - NetSuite Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive myDials Demo Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive myDials NetSuite Module Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive myDials Online Module Trial Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive myDials Webinar Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive Roadshow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP BPK Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP CPM Brochure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Customer Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Discovery Free Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Enterprise Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Express - Downloaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Express - Hosted Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Group Demo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Live Demo Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Partner Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Pre-Recorded Consolidation Webinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Pre-Recorded Discovery Webinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Pre-Recorded Online Demo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Pre-Recorded Prospect Webinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Resource Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Survival Kit Demo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived Webinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beta Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Software WP - Top 10 Financial Management Vendors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Software WP - Top 15 Accounting Software Vendors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case study</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is used by SDRs to track the SDR lifecycle</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <controllingField>Lifecycle_Stage__c</controllingField>
            <picklistValues>
                <fullName>Raw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restored</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Offer_Most_Recent__c</fullName>
        <inlineHelpText>this value should change over time given that the person keeps getting new material</inlineHelpText>
        <label>Lead Offer - Most Recent</label>
        <picklist>
            <picklistValues>
                <fullName>Adaptive Live 2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive myDials Contact Me Form - General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive myDials Contact Me Form - NetSuite Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive myDials Demo Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive myDials NetSuite Module Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive myDials Online Module Trial Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive myDials Webinar Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive Roadshow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP BPK Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP CPM Brochure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Customer Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Discovery Free Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Enterprise Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Express - Downloaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Express - Hosted Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Group Demo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Live Demo Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Partner Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Pre-Recorded Consolidation Webinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Pre-Recorded Discovery Webinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Pre-Recorded Online Demo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Pre-Recorded Prospect Webinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Resource Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP Survival Kit Demo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived Webinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beta Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Software WP - Top 10 Financial Management Vendors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Software WP - Top 15 Accounting Software Vendors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case study</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/BatchContactDailySummaryCSM.cls
/**@@
#Batch CLASS NAME  : BatchContactDailySummary
#DESCRIPTION       : This is Batch class used to send an Email to Account owners.
An email containing a digest of all new contacts on accounts within the past 24 hours.
@@**/

public class BatchContactDailySummaryCSM implements Database.Batchable<sObject>
{
    /**@@
#DESCRIPTION     : This is start method which return the user records.
#Paramaters      : (Database.BatchableContext bc) It is a reference to the Database.BatchableContext object 
@@**/
    public Database.QueryLocator start(Database.BatchableContext bc)
    { 
        Map<Id, Id> mapOwnerIds = new Map<Id, Id>();
        
        //select accounts which has contacts created within in 24 hr.
        Datetime dt = System.now()-1;
        List<Account> accs = [SELECT Account_CSM__c,id FROM Account WHERE Id IN (SELECT accountId FROM Contact WHERE CreatedDate >=: dt)];
        
        for(Account acc : accs)
            mapOwnerIds.put(acc.Account_CSM__c, acc.Id);
        
        Set<Id> setOwnerIds = mapOwnerIds.keySet(); // this is de-duping account owners
        
        String query = 'SELECT Id FROM User WHERE Id IN :setOwnerIds';
        
        return Database.getQueryLocator(query);
    }//End of start method
    
    /**@@
#DESCRIPTION     : This is execute method, which is used to send an E-mail to Account CSM of the account. 
#Paramaters      :  1)BC (Database.BatchableContext) : It is a reference to the Database.BatchableContext object.
2)List<Account> lstAcc : List of users.
@@**/
    public void execute(Database.BatchableContext bc,List<User> lstUsers)
    {       
        
        Datetime dt = System.now()-1;
        Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
        Map <id, list<Contact>> MapContact = new Map <id, list<Contact>>();
        List<Contact> listInnerContact = new List<Contact>();
        string htmlBody='' ;
        
        for(User u:lstUsers){
                     
            list<Contact> conList =[SELECT id,Name,Accountid,Account.name,Account.Owner.name,Status__c,Account.Account_CSM__c,Lead_Offer_Most_Recent__c,Title,Account_Type__c,Calculated_Score__c FROM Contact WHERE CreatedDate >=: dt AND Account.Account_CSM__c =:u.id  ];
           
            if(!conList.isEmpty()){
                htmlBody= '<h2>Summary of Contacts Created Within Last Day </h2>'+
                    '<p>You are receiving this email because in the last day a new contact was created on an account on which you are as a Account CSM. '+
                    'If the status is equal to New, you have 2 days to review the contact and move it to Qualified, Unqualified or Unresponsive. '+
                    '<table border="1" style="border-collapse: collapse" cellpadding="3">'+
                    '<tr><th>Contact Name</th>'+
                    '<th>Title</th>'+
                    '<th>Account Name</th>'+
                    '<th>Lead Score</th>'+
                    '<th>Contact Status</th>'+
                    '<th>Account Type</th>'+
                    '<th>Account Owner</th>'+
                    '<th>Lead Offer - Most Recent</th>'+
                    '</tr>';
                for(integer i=0;i<conList.size();i++)
                {
                    if(conList[i].Title == null)
                        conList[i].Title = '';
                    if(conList[i].Lead_Offer_Most_Recent__c == null)
                        conList[i].Lead_Offer_Most_Recent__c = '';
                    htmlBody+= '<tr><td><a href="'+System.URL.getSalesforceBaseUrl().toExternalForm()+'/'+conList[i].id+'">' +conList[i].Name+ '</a></td>'+
                        '<td>'+ conList[i].Title+'</td>'+
                        '<td><a href="'+System.URL.getSalesforceBaseUrl().toExternalForm()+'/'+conList[i].AccountId+'">' + conList[i].Account.name + '</td>'+
                        '<td>' + conList[i].Calculated_Score__c + '</td>'+
                        '<td>' + conList[i].Status__c + '</td>'+
                        '<td>' + conList[i].Account_Type__c + '</td>'+
                        '<td>' + conList[i].Account.Owner.Name + '</td>'+
                        '<td>' + conList[i].Lead_Offer_Most_Recent__c + '</td>'+
                        '</tr>';
                }//End of For
                
            }//End of If  
            mail.setTargetObjectId(u.id);
            mail.setHtmlBody(htmlBody);   
            mail.setSaveAsActivity(false);
            mail.setSubject('New Contacts Created - Action Required for New Status');
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            htmlBody='';
        }//End of For
    }//End of Execute() method
    
    /**@@
#DESCRIPTION     :  It is a finish method of batch class. used for None purpose but its required in batch class.
#Paramaters      :  BC (Database.BatchableContext) : It is a reference to the Database.BatchableContext object 
@@**/
    public void Finish(Database.BatchableContext bc)
    {
        
    }//End of finish method
}//End of BatchDailySummary class