AI-JADEDEVS4/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Lifecycle_Stage__c</fullName>
        <inlineHelpText>Marketing Accepted Lead (MAL) 
Marketing Qualified Lead (MQL) 
Sales Accepted Lead (SAL) 
Sales Qualified Lead (SQL) 
Customer</inlineHelpText>
        <label>Lifecycle</label>
        <picklist>
            <picklistValues>
                <fullName>MAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is used by SDRs to track the SDR lifecycle</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <controllingField>Lifecycle_Stage__c</controllingField>
            <picklistValues>
                <fullName>Raw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restored</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Timestamp_Lifecycle_MQL__c</fullName>
        <label>Timestamp Lifecycle MQL</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lifecycle_Stage__c</fullName>
        <inlineHelpText>Marketing Accepted Lead (MAL)
Marketing Qualified Lead (MQL)
Sales Accepted Lead (SAL)</inlineHelpText>
        <label>Lifecycle</label>
        <picklist>
            <picklistValues>
                <fullName>MAL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>MQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Timestamp_Lifecycle_MQL__c</fullName>
        <label>Timestamp Lifecycle MQL</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/SkipAutomationSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used in all triggers, Workflow rules and validation rules.</description>
    <fields>
        <fullName>Contact_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact Automation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Automation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opportunity Automation</label>
        <type>Checkbox</type>
    </fields>
    <label>Skip Automation Setting</label>
</CustomObject>

AI-JADEDEVS4/src/classes/BatchSLA_Notification_Manager_Test.cls
/**@@
#CLASS NAME     :   BatchSLA_Notification_Manager_Test
#DESCRIPTION    :   This is a test class for BatchDailySummary batch class.
@@**/

@isTest
public class BatchSLA_Notification_Manager_Test {
    /**@@
#DESCRIPTION     : This is a test method used to create test data for BatchDailySummary batch class.
#Paramaters      : None
@@**/
    static testMethod void SLANOtification_Manager_test() 
    {
        DataFactory.insertCustomSetting();
        SkipAutomationSetting__c customSettingObj = SkipAutomationSetting__c.getOrgDefaults();
        customSettingObj.Lead_Automation__c =false;
        customSettingObj.Contact_Automation__c = false;
        customSettingObj.Opportunity_Automation__c =false;
        upsert customSettingObj;
        
        //insert businessdays custom setting
     	DataFactory.createBusinessDays();
     
        //Insert acount
        List<Account> accList = DataFactory.createAccountTestRecords('testaccountcompany',1);
       
        //insert Lead
        List<Lead> leadList = DataFactory.createLeadTestRecords('leadLastName', 1);
        leadList[0].Status =CustomConstants.LeadStatusNew;
        dateTime dt =system.now().addDays(-4);
        leadList[0].Timestamp_Lifecycle_MQL__c =dt;
        leadList[0].Lifecycle_Stage__c = CustomConstants.LifecycleMQL;
        update leadList;
        
        //Insert contact
        List<Contact> conList=DataFactory.createContactTestRecords('Test Contact',accList[0].Id,1);
        conList[0].Status__c = CustomConstants.ContactStatusRestored;
        conList[0].Timestamp_Lifecycle_MQL__c= system.now().addDays(-4);
        conList[0].Lifecycle_Stage__c = CustomConstants.LifecycleMQL;
        update conList; 
        
        //insert opportunity
        List<Opportunity> OppList = DataFactory.createOpportunityTestRecords1('opportunityName', 2);
        OppList[0].StageName = CustomConstants.OpportunityStageProspect;
        OppList[1].StageName = CustomConstants.OpportunityStageSAO;
        OppList[0]. First_Meeting_Date__c = system.Today().addDays(-20);
      OppList[1]. Timestamp_SAO__c  =system.Today().addDays(-20);
        update  OppList;
        
        Test.StartTest();
        BatchSLA_Notification_ManagerScheduler objschclass = new BatchSLA_Notification_ManagerScheduler();
        String cronexpression ='0 0 9 ? * THU';
        system.schedule('BatchSLA_Notification Manager', cronexpression, objschclass);
        Test.stopTest();
        
    }//End of SLANOtification_test 
}//End of class