AI-JADEDEVS4/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <businessProcess>Indirect Sales</businessProcess>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/IndirectLeadAction_Tests.cls
@IsTest
public class IndirectLeadAction_Tests {
	@TestSetup static void init() {
		TestData.initTriggerSettings();
	}
    
    @IsTest public static void leadConversionTests(){
        Account testAccount = new Account(Name= 'Test Account Company',                                           
                                          Status__c='Active',                                          
                                          BillingCountry='USA',
                                          BillingPostalCode='12345');
		insert testAccount;
        System.assert(testAccount != null);
        
        Lead testLead = new Lead(Company='Test Account Company',
                        FirstName = 'LeadFName',
                        LastName='LName',
                        Country='USA',
                        Website = 'www.company.com',
                        PostalCode = '12345',
                        Email='testemail@test.com',
						Type__c='Customer Prospect');
		insert testLead;
        System.assert(testLead != null);
        
        IndirectLeadAction.process(new List<Lead>{ testLead });
        
        testLead = (Lead)SObjectUtils.get('Lead', testLead.Id);
        //System.assertEquals(true, testLead.IsConverted);
        
        //System.assert( Database.countQuery('SELECT Count() FROM CampaignMember') > 0);
        //System.assert(Database.countQuery('SELECT Count() FROM Opportunity WHERE Partner_Opportunity__c=True') > 0);
    }
    
    @IsTest public static void leadWebsiteAccountMatchTests(){
        Account testAccount = new Account(Name= 'Test Account Company',                                           
                                          Status__c='Active',                                          
                                          Website = 'http://www.company.com',
                                          BillingCountry='USA',
                                          BillingPostalCode='12345');
		insert testAccount;
        System.assert(testAccount != null);
        
        Lead testLead = new Lead(Company='Test Account Company',
                        FirstName = 'LeadFName',
                        LastName='LName',
                        Country='USA',
                        Website = 'www.company.com',
                        PostalCode = '12345',
                        Email='testemail@test.com');
		insert testLead;
        System.assert(testLead != null);
        IndirectLeadAction.process(new List<Lead>{ testLead });
        
        testLead = (Lead)SObjectUtils.get('Lead', testLead.Id);
        System.assertEquals(false, testLead.IsConverted);
        System.assertEquals(IndirectLeadAction.ChannelLead_QueueID, testLead.OwnerId);
    }
}