AI-JADEDEVS4/src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Migration_ID__c</fullName>
        <description>Migration source.</description>
        <externalId>true</externalId>
        <label>Migration ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Old_ID__c</fullName>
        <externalId>true</externalId>
        <label>Old ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Enterprise_Trial__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>requested for the Enterprise Trial on our website and or doing custome Trial from other means (like from pre-sales)</inlineHelpText>
        <label>Enterprise Trial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Old_ID__c</fullName>
        <externalId>true</externalId>
        <label>Old ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Reason_for_Recycled__c</fullName>
        <description>Returns the lead to marketing to fix or wait until prospect re-engages. Must define why you Recycled.</description>
        <inlineHelpText>Returns the lead to marketing to fix or wait until prospect re-engages. Must define why you Recycled.</inlineHelpText>
        <label>Reason for Recycled</label>
        <picklist>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Phone Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Title/Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer With Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add to Lead Nurture Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trial_Created_Date__c</fullName>
        <label>Trial Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Key__c</fullName>
        <label>Trial Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Username__c</fullName>
        <label>Trial Username</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>X1st_Meeting_Completed_Date__c</fullName>
        <label>1st Meeting Attended Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X1st_Meeting_Credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter name of User who gets credit for the 1st Meeting</description>
        <inlineHelpText>Enter the SFDC User who gets credit for this 1st Meeting</inlineHelpText>
        <label>1st Meeting Credit</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X1st_Meeting_Reschedules__c</fullName>
        <defaultValue>0</defaultValue>
        <label>1st Meeting Reschedules</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1st_Meeting_Scheduled_Date__c</fullName>
        <description>Date 1st Meeting is schedlued</description>
        <inlineHelpText>Enter the date the 1st Meeting is scheduled for</inlineHelpText>
        <label>1st Meeting Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X1st_Meeting_Source__c</fullName>
        <inlineHelpText>What was the source of this 1st meeting and who generated it.</inlineHelpText>
        <label>1st Meeting Source</label>
        <picklist>
            <picklistValues>
                <fullName>SD-Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SD-Self Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SD-Inbound Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field-Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field-Self Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field-Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Old_ID__c</fullName>
        <externalId>true</externalId>
        <label>Old ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/LeadActivityBatch.cls
/**@@
#BATCH CLASS NAME  :    LeadActivityBatch
#DESCRIPTION       :    This batch class is used to create 4 Event Activities related to lead record where “old Id” field value on Lead is not equal to NULL. 
						Those 4 Events are as follows: 
                            •	Create event activity for first meeting,
                            •	Create event activity for completed meeting date,
                            •	Create event activity for trial,
                            •	Create event activity for Reason Recycled.
                              
@@**/

global class LeadActivityBatch implements Database.Batchable<sObject> {

    /**@@
    #DESCRIPTION     : This is a Start method of Batch class which returns a String of leads with respective fields used in query where Old ID is not equal to Null.
    #Paramaters      : BC (Database.BatchableContext) : It is a reference to the Database.BatchableContext object.
    @@**/
	global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        String query = 'SELECT Id,Name,CreatedDate,' +
                'x1st_meeting_completed_date__c,x1st_meeting_credit__c,X1st_Meeting_Credit__r.Name,x1st_meeting_reschedules__c,x1st_meeting_scheduled_date__c,x1st_meeting_source__c,' + 
                'enterprise_trial__c,trial_created_date__c,trial_key__c,trial_username__c,reason_for_recycled__c FROM Lead WHERE Old_ID__c!=null';
        //returns a list of leads with respective fields used in query where Old ID is not equal to Null.
        return Database.getQueryLocator(query); 
        
    }//End start method

    /**@@
    #DESCRIPTION     : This method return a list of leads from Start method and creates 4 event activities for those retured lead records.those 4 event activies are created for first meeting, completed meeting date, trial, Reason Recycled.
    #Paramaters      : 1) BC (Database.BatchableContext) : It is a reference to the Database.BatchableContext object.
					   2) scope(List<Lead>)	             : It is used to take a list of leads which are returned from start method of batch class. 
    @@**/
	global void execute(Database.BatchableContext BC, List<Lead> scope) 
    {
        List<Event> upsertEvents = new List<Event>();
        for(Lead l : scope)
        {
            // Create event activity for first meeting
            if(l.x1st_meeting_scheduled_date__c != null){
                Event evt = new Event();
                evt.WhoId = l.Id;
                evt.Subject = 'Scheduled First Meeting';
                evt.Type = 'Meeting';
                evt.StartDateTime = l.x1st_meeting_scheduled_date__c;
                evt.DurationInMinutes = 60;
                evt.Description = 'Meeting source: ' + l.x1st_meeting_source__c + '\r' +
                        'Credited To: ' + l.x1st_meeting_credit__r.Name + '\r' +
                        'Reschedule Notes: ' + l.x1st_meeting_reschedules__c;
                evt.Migration_ID__c = l.Id + ':1stMeeting';
                upsertEvents.add(evt);
            }//End of if loop
            
            // Create event activity for completed meeting date
            if(l.x1st_meeting_completed_date__c != null)
            {
                Event evt = new Event();
                evt.WhoId = l.Id;
                evt.Subject = 'First Meeting Completed';
                evt.Type = 'Meeting';
                evt.StartDateTime = l.x1st_meeting_completed_date__c;
                evt.EndDateTime = l.x1st_meeting_completed_date__c;
                evt.Description = '(Migrated from old Salesforce Org)';
                evt.Migration_ID__c = l.Id + ':1stMeetingCompleted';
                upsertEvents.add(evt);
            }//End of if loop
            
            // Create event activity for trial
            if(l.trial_created_date__c != null)
            {                
                Event evt = new Event();
                evt.WhoId = l.Id;
                evt.Subject = 'Trial Created';
                evt.Type = 'Trial';
                evt.StartDateTime = l.trial_created_date__c;
                evt.DurationInMinutes = 60;
                evt.Description = 'Trial user: ' + l.trial_username__c + ' with trial key: ' + l.trial_key__c;
                evt.Migration_ID__c = l.Id + ':TrialCreated';
                upsertEvents.add(evt);
            }//End of if loop
            
            // Create event activity for Reason Recycled
            if(l.reason_for_recycled__c != null)
            {               
                Event evt = new Event();
                evt.WhoId = l.Id;
                evt.Subject = 'Lead Recycled (Archived)';
                evt.Type = 'Other';
                evt.StartDateTime = l.CreatedDate;
                evt.DurationInMinutes = 60;
                evt.Description = 'Archived note: Lead was recycled in previous Salesforce org. Reason: ' + l.Reason_for_Recycled__c;
                evt.Migration_ID__c = l.Id + ':ReasonRecycled';
                upsertEvents.add(evt);
            }//End of if loop
        }//End of for loop
        // Prevents creating multiple activities on subsequent executions (intended to be one-time only migration)
        upsert upsertEvents Migration_ID__c; 
    
    }//End of execute method

	/**@@
    #DESCRIPTION     : This is a finish method of batch class, which executes after excution of execute method of batch class. 
    #Paramaters      :  BC (Database.BatchableContext) : It is a reference to the Database.BatchableContext object 
    @@**/
    global void finish(Database.BatchableContext BC) 
    {

    }//End of finish method
}//End of batch class