AI-JADEDEVS4/src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Determines if a Zipcode is actively associated with a territory.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AreaCode__c</fullName>
        <label>Area Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>2 character ISO Code. Actual name country is defined on the record &quot;Name&quot; field.</description>
        <inlineHelpText>2 character ISO Code. Actual name country is defined on the record &quot;Name&quot; field.</inlineHelpText>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Unique key consisting of State, ZipCode, AreaCode, and City.</inlineHelpText>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>ZipCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NAICS_Code__c</fullName>
        <inlineHelpText>Mapped to Account.NAICS_Code from Data.com</inlineHelpText>
        <label>NAICS Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Role__c</fullName>
        <label>Owner Role</label>
        <picklist>
            <picklistValues>
                <fullName>SDR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Account Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Queue_ID__c</fullName>
        <inlineHelpText>Represents the assignment queue (requires cut-n-paste of ID. Lookup reference to Queues not supported).</inlineHelpText>
        <label>Default Queue ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Band__c</fullName>
        <description>Refactor to multiple band examples 0-50M,50-100M,100-200M</description>
        <label>Revenue Band</label>
        <picklist>
            <picklistValues>
                <fullName>Below $100M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Above $100M</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Territory_Owner__c</fullName>
        <formula>IF( ISBLANK( Queue_ID__c ), &quot;User&quot;, &quot;Queue&quot; )</formula>
        <label>Territory Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The default User who owns assignments to this territory.</inlineHelpText>
        <label>Default Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Territory_Area__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Territory Areas</relationshipLabel>
        <relationshipName>Territory_Areas</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Areacode__c</fullName>
        <formula>Area__r.AreaCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Area__r.Country__c</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <formula>Area__r.County__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Enforces one area per territory type (Lead, CSM). Prevents duplicate areas from being assigned.</inlineHelpText>
        <label>Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NAICS_Code__c</fullName>
        <formula>Territory__r.NAICS_Code__c</formula>
        <label>NAICS Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Area__r.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <formula>Territory__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Territory Areas</relationshipLabel>
        <relationshipName>Territory_Areas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <formula>Area__r.ZipCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zipcode</label>
        <type>Text</type>
    </fields>
    <label>Territory Area</label>
    <nameField>
        <displayFormat>TerritoryArea-{00000000}</displayFormat>
        <label>Territory Area ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/TerritoryManagerController.cls
global class TerritoryManagerController {
    public final String TERRITORY_JSON {get;set;}
    
    public TerritoryManagerController(){
        List<Territory__c> allTerritories = [SELECT Id,Name,User__c,User__r.Name,Queue_ID__c,Territory_Owner__c,Owner_Role__c,Revenue_Band__c,NAICS_Code__c,Active__c FROM Territory__c WHERE Active__c=True ORDER BY Name];
        TERRITORY_JSON = JSON.serialize(allTerritories).replace('\'', '');
    }
    
    @RemoteAction
    global static List<Territory_Area__c> getTerritoryAreas(String territoryId){
        return [SELECT Id, Area__c,Territory__c,TerritoryName__c,Country__c,State__c,County__c,Zipcode__c,AreaCode__c FROM Territory_Area__c WHERE Territory__c=:territoryId ORDER BY Zipcode__c];
    }
        
    @RemoteAction
    global static List<Area__c> searchAreas(String territoryId, String field, String searchTerm){
        String soql = 'SELECT Id,Active__c,Name,State__c,Country__c,County__c,City__c,ZipCode__c,AreaCode__c FROM Area__c ' + 
            'WHERE ' + field + ' LIKE \'' + searchTerm + '\' ORDER BY ' + field;
        return Database.query(soql);
    }
    
    /*
     * TODO: Handle use case where area is already assigned (Currently throws an exception)
     */
    @RemoteAction
    global static String assignAreas(String territoryId, List<String> areaList){
        Territory__c t = [SELECT Id,Name,User__c,User__r.Name,Queue_ID__c,Territory_Owner__c,Owner_Role__c,Revenue_Band__c,NAICS_Code__c,Active__c FROM Territory__c WHERE Id=:territoryId LIMIT 1];
        List<Territory_Area__c> territoryAreaList = new List<Territory_Area__c>();
        for(String areaId : areaList){
            String key = areaId + ':' + 
                (t.Owner_Role__c == null ? 'all-roles':t.Owner_Role__c) + ':' + 
                (t.Revenue_Band__c == null ? 'all-revbands':t.Revenue_Band__c) + ':' + 
                (t.NAICS_Code__c == null ? 'all-industries':t.NAICS_Code__c);
            Territory_Area__c ta = new Territory_Area__c();
            ta.Territory__c = territoryId;
            ta.Area__c = areaId;
            ta.Key__c = key; // Enforce one role type per area. e.g. Only one 'SDR' assigned
            territoryAreaList.add(ta);
        }
        upsert territoryAreaList;
        return 'ok. List size ' + areaList.size();
    }
    
    @RemoteAction
    global static String deleteTerritoryAreas(String territoryId, List<String> taList){
        DELETE [SELECT Id FROM Territory_Area__c WHERE Id IN :taList]; 
        return 'ok. List size ' + taList.size();
    }
}