AI-JADEDEVS4/src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>ZipCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Territory_Area__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Territory Areas</relationshipLabel>
        <relationshipName>Territory_Areas</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <formula>Area__r.ZipCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zipcode</label>
        <type>Text</type>
    </fields>
    <label>Territory Area</label>
    <nameField>
        <displayFormat>TerritoryArea-{00000000}</displayFormat>
        <label>Territory Area ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/TerritoryManagerController_Tests.cls
@IsTest
public class TerritoryManagerController_Tests {

    @TestSetup static void init() {
        TestData.setup();
    }
    
    @IsTest public static void basicTests(){
        TestData data = new TestData();
        TerritoryManagerController ctrl = new TerritoryManagerController();
        
        List<Territory_Area__c> areas = TerritoryManagerController.getTerritoryAreas( data.TestTerritories[0].Id );
        System.assertEquals(3, areas.size());
        
        areas = TerritoryManagerController.getTerritoryAreas( data.TestTerritories[1].Id );
        System.assertEquals(7, areas.size());
        
        List<Area__c> searchResults = TerritoryManagerController.searchAreas(data.TestTerritories[0].Id, 'Zipcode__c', '50%');
        System.assertEquals(5, searchResults.size() );
        
        // Assign an existing area to an Territory
        String response = TerritoryManagerController.assignAreas(data.TestTerritories[1].Id, new List<String>{ data.TestAreas[0].Id } );
        System.assert(response != null);
        
        response = TerritoryManagerController.deleteTerritoryAreas(data.TestTerritories[0].Id, new List<String>{ data.TestTerritoryAreas[0].Id });
        System.assert(response != null);
    }
}