AI-JADEDEVS4/src/objects/Booking_Detail__c.object
<CustomObject>
    <description>Created upon Opportunity Closed-Won
- opp id
- New logo ARR
- Add-on ARR
- total New ARR (New logo ARR + Add- on ARR)
- Service
- Scheduled Renewal ARR (Installments)
- Renewal ARR (Scheduled Renewal ARR+ Contract ARR)
- ACV (Total New ARR + Renewal ARR + Service)
- New MYR
- Renewal MYR
- Total MYR (New MYR + Renewal MYR)
- Total Bookings (Total New ARR + Services + Scheduled Renewal ARR + Total MYR)
- Unbilled
- TCV Bookings (Total Bookings + Unbilled)
- Subscription Start
- Subscription End</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Closed Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking Details</relationshipLabel>
        <relationshipName>Booking_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Booking Details</relationshipLabel>
        <relationshipName>Booking_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The primary quote from which this booking detail was generated.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Booking Details</relationshipLabel>
        <relationshipName>Booking_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking Detail</label>
    <nameField>
        <displayFormat>Booking-{000000}</displayFormat>
        <label>Booking Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Installment__c.object
<CustomObject>
    <description>Represents a single payment installment for a Multi-Year Opportunity/Order.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Quote__r.SBQQ__Opportunity2__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Master Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Due_Amount__c</fullName>
        <label>Payment Due Amount</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Due_Date__c</fullName>
        <label>Payment Billing Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Installments</relationshipLabel>
        <relationshipName>Installments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Installment</label>
    <nameField>
        <displayFormat>Installment-{0000000}</displayFormat>
        <label>Installment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term_Years__c</fullName>
        <formula>Term_Months__c / 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term Years</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/AIWrapperClassTests.cls
@IsTest
public class AIWrapperClassTests {

    @TestSetup static void init() {
        TestData.setup();
    }
    
    @IsTest public static void basicTests(){        
        TestData data = new TestData();
                
        data.TestQuote.Term_Years__c = '3';
        data.TestQuote.SBQQ__SubscriptionTerm__c = 36;
        data.TestQuote.Is_Multi_Year__c = True;
        update data.TestQuote;
        data.TestOpportunity = (Opportunity) SObjectUtils.get('Opportunity', data.TestOpportunity.Id);      
        System.assertEquals(3, data.TestOpportunity.Term_Years__c);
        System.assert( data.TestOpportunity.Roll_Up_Subscription_Revenue__c > 0);
        System.assert( data.TestOpportunity.SBQQ__PrimaryQuote__c != null);
        
        AIOpportunity oppty = new AIOpportunity().withSObject(data.TestOpportunity);
        System.assertEquals(data.TestOpportunity.Id, oppty.Id);
        System.assert(oppty.LineItems.size() > 0);
        oppty = new AIOpportunity().withId(data.TestOpportunity.Id);
        System.assertEquals(data.TestOpportunity.Id, oppty.Id);
        System.assert(oppty.LineItems.size() > 0);
        
        oppty.clearErrors();
        System.assertEquals(false, oppty.hasErrors());        
        
        List<OpportunityLineItem> items = oppty.LineItems.values();
        AIOpportunityLineItem lineItem = new AIOpportunityLineItem().withSObject(items[0] );
        System.assert(lineItem != null);
        lineItem = new AIOpportunityLineItem().withId(items[0].Id);
        System.assert(lineItem != null);
        
        OpportunityOrderConversionAction.convertToOrder(new List<Opportunity>{ data.TestOpportunity});
        Id orderId = [SELECT Id FROM Order][0].Id;
        AIOrder order = new AIOrder().withId(orderId);
        System.assert(order != null);
        System.assert(order.OrderItems.size() > 0);
        System.assert( order.Id == orderId );
        System.assert( order.record.Id == orderId );
        order = new AIOrder().withSObject(order.record);
        System.assert(order != null);
        
        List<OrderItem> oitems = order.OrderItems.values();
        AIOrderItem orderItem = new AIOrderItem().withSObject( oitems[0] );
        System.assert( orderItem != null );
        orderItem = new AIOrderItem().withId( oitems[0].Id );
        System.assert( orderItem != null );
        
        Booking_Detail__c detail = new Booking_Detail__c();
        detail.Opportunity__c = data.TestOpportunity.Id;
        detail.Order__c = orderId;
        insert detail;
        AIBookingDetail bookingDetail = new AIBookingDetail().withSObject(detail);
        System.assert(bookingDetail != null);
        bookingDetail = new AIBookingDetail().withId(detail.Id);
        System.assert(bookingDetail != null);
        
        List<Installment__c> testInstallments = new List<Installment__c>();
        for(Integer i=0; i<3; i++){
            Installment__c iRecord = new Installment__c();
            iRecord.Quote__c = data.TestQuote.Id;
            iRecord.Payment_Due_Amount__c = 1000.00;
            iRecord.Payment_Due_Date__c = Date.today().addYears(i+1);
            testInstallments.add(iRecord);
        }
        insert testInstallments;
        
        AIInstallment installment = new AIInstallment().withSObject(testInstallments[0]);
        System.assert( installment != null );
        installment = new AIInstallment().withId(testInstallments[0].Id);
        System.assert( installment != null );
        
        SBQuote quote = new SBQuote().withSObject(data.TestQuote);
        System.assertEquals(3, quote.Installments.size());
    }
}