AI-JADEDEVS4/src/objects/Booking_Detail__c.object
<CustomObject>
    <description>Created upon Opportunity Closed-Won
- opp id
- New logo ARR
- Add-on ARR
- total New ARR (New logo ARR + Add- on ARR)
- Service
- Scheduled Renewal ARR (Installments)
- Renewal ARR (Scheduled Renewal ARR+ Contract ARR)
- ACV (Total New ARR + Renewal ARR + Service)
- New MYR
- Renewal MYR
- Total MYR (New MYR + Renewal MYR)
- Total Bookings (Total New ARR + Services + Scheduled Renewal ARR + Total MYR)
- Unbilled
- TCV Bookings (Total Bookings + Unbilled)
- Subscription Start
- Subscription End</description>
    <fields>
        <fullName>Free_Months__c</fullName>
        <description>Gets the free months from the primary quote on the related opportunity</description>
        <formula>Value(Text(Opportunity__r.SBQQ__PrimaryQuote__r.Free_Months__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Free Months on the related quote</inlineHelpText>
        <label>Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Add_On_Booking__c</fullName>
        <formula>IF( TEXT(Opportunity__r.Type) = &apos;Add-On&apos;, 
True, 
False 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Add-On Booking?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Renewal_Booking__c</fullName>
        <formula>IF( TEXT(Opportunity__r.Type) = &apos;Renewal&apos;, 
True, 
False 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Renewal Booking?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MYR_Term__c</fullName>
        <formula>IF( Is_First_Year__c ,
  IF( Renewal_Term__c  &gt;12,
      Renewal_Term__c - 12,
      0),
  0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MYR Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Closed Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking Details</relationshipLabel>
        <relationshipName>Booking_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Booking Details</relationshipLabel>
        <relationshipName>Booking_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Renewal_Term__c</fullName>
        <description>Term the renewal opportunity will get without any free months</description>
        <formula>Opportunity__r.Renewal_Term__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Renewal Term length minus free months</inlineHelpText>
        <label>Renewal Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Term_Months__c</fullName>
        <inlineHelpText>Total subscription term length including free months.</inlineHelpText>
        <label>Subscription Term Months</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Renewal_ARR__c</fullName>
        <formula>Opportunity__r.Target_Renewal_ARR__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Target Renewal ARR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Temp_AddOn_ARR__c</fullName>
        <description>This is only to hold values for formulas</description>
        <label>Temp Add-on ARR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Temp_Annualized_Subscription_Revenue__c</fullName>
        <label>Temp Annualized Subscription Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Temp_Renewal_ARR__c</fullName>
        <description>This is updated by a workflow</description>
        <label>Temp Renewal ARR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Temp_Total_Bookings__c</fullName>
        <inlineHelpText>Used to store the calculated Total Bookings driven by a workflow</inlineHelpText>
        <label>Temp Total Bookings</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_New_Booking__c</fullName>
        <formula>Total_New_ARR__c + New_MYR__c + Service_Bookings__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total New ARR + New MYR + Service Bookings</inlineHelpText>
        <label>Total New Booking</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Renewal_Booking__c</fullName>
        <formula>Renewal_ARR__c +  Renewal_MYR__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Renewal Booking</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Booking Detail</label>
    <nameField>
        <displayFormat>Booking-{000000}</displayFormat>
        <label>Booking Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Free_Months__c</fullName>
        <formula>VALUE(TEXT(Quote__r.Free_Months__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Free Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal_term__c</fullName>
        <formula>Opportunity.Renewal_Term__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term_Months__c</fullName>
        <formula>Quote__r.Quote_Term_Length__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Subscription_Revenue__c</fullName>
        <inlineHelpText>SUM of all Subscription line items</inlineHelpText>
        <label>Total Subscription Revenue</label>
        <summarizedField>OrderItem.Total_Price_AI__c</summarizedField>
        <summaryFilterItems>
            <field>OrderItem.Revenue_Type__c</field>
            <operation>equals</operation>
            <value>Subscription</value>
        </summaryFilterItems>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/Trigger_BookingDetail_Helper.cls
/**@@
#TRIGGER NAME          :    BookingDetailTrigger
#HANDLER CLASS NAME    :    Trigger_BookingDetail_Handler
#HELPER CLASS NAME     :    Trigger_BookingDetail_Helper
#DESCRIPTION           :    This Trigger will handles all the trigger events and make call to the Handler class to handling the appropriate logic.
@@**/
public class Trigger_BookingDetail_Helper {
      
    public static boolean bookingDetailTriggerHandler_flag = false;
    public Trigger_BookingDetail_Helper(){

    }
    /**@@
        #DESCRIPTION     : This method is used to update Booking detail information based on relate Order and Opportunity information
        #Paramaters      : map<ID, Booking_Detail__c> newmap, map<ID, Booking_Detail__c> oldmap
        #Return type     : void
    @@**/
    public static void onAfterInsertUpdate(map<ID, Booking_Detail__c> newmap, map<ID, Booking_Detail__c> oldmap) {
            
         list<Booking_Detail__c> bookingDetailsUpdate = new list<Booking_Detail__c>();
         set<Id> sOrderId = new set<Id>();
         set<Id> sOppId = new set<Id>();
         
         for(Booking_Detail__c bd : newmap.values()) {
             if(bd.Order__c != null){
                 sOrderId.add(bd.Order__c);
             }
             if(bd.Opportunity__c != null){
                 sOppId.add(bd.Opportunity__c);
             }
         }
         // Fetch Existing Order related to Booking Detail
         Map<Id, Order> mapOrderList = new Map<Id, Order>();
         if(!sOrderId.isEmpty()){
             mapOrderList = new Map<Id, Order>([Select Id, Term_Months__c, Free_Months__c, Renewal_Term__c, Total_Subscription_Revenue__c from Order where Id IN: sOrderId]);
         }
         
         // Fetch Existing Opportunity related to Booking Detail
         Map<Id, Opportunity> mapOpportunityList = new Map<Id, Opportunity>();
         if(!sOppId.isEmpty()){
             mapOpportunityList = new Map<Id, Opportunity>([Select Id, Renewal_Term__c, Target_Renewal_ARR__c, SBQQ__PrimaryQuote__r.Id, Total_Subscription_Revenue__c from Opportunity where Id IN: sOppId]);
         }
            
         for(Booking_Detail__c bd : newmap.values()) {
            Booking_Detail__c objBD = new Booking_Detail__c(ID=bd.ID);            
            
            double asr = 0.00;
            double myr = 0.00;
            double tadd = 0.00;
            double trenewal = 0.00;
            double tsubbooking = 0.00;
            double renewalTerm = 0.00;
            double annualTerm = 0.00;
            
            if(bd.Order__c != null && mapOrderList.containsKey(bd.Order__c)){
                Order relatedOrder = mapOrderList.get(bd.Order__c);
                if ((relatedOrder.Term_Months__c - relatedOrder.Free_Months__c) > 12){
                    renewalTerm = relatedOrder.Term_Months__c - relatedOrder.Free_Months__c;
                } else {
                    renewalTerm = 12;
                }
    
                if (relatedOrder.Term_Months__c > 12) {
                    annualTerm = 12;
                } else {
                    annualTerm = relatedOrder.Term_Months__c;
                }
    
                asr = (relatedOrder.Total_Subscription_Revenue__c/relatedOrder.Term_Months__c) * annualTerm;
                myr = (relatedOrder.Total_Subscription_Revenue__c/relatedOrder.Term_Months__c) * bd.MYR_Term__c;
                
                objBD.Subscription_Term_Months__c = relatedOrder.Term_Months__c;
            }
            
            if(bd.Opportunity__c != null && mapOpportunityList.containsKey(bd.Opportunity__c)){
                Opportunity relatedOpp = mapOpportunityList.get(bd.Opportunity__c);
            
                if(bd.Is_Add_On_Booking__c) {
                    tadd = asr;
                } else {
                    IF(bd.Is_Renewal_Booking__c) {
                        IF(asr > relatedOpp.Target_Renewal_ARR__c) {
                            tadd = asr - relatedOpp.Target_Renewal_ARR__c;
                            } else {
                                tadd = 0;
                            }
                    } else {
                        tadd = 0;
                    }
                }

                if(bd.Is_Renewal_Booking__c){
                    if((asr - relatedOpp.Target_Renewal_ARR__c) > 0){
                        trenewal = relatedOpp.Target_Renewal_ARR__c;
                    } else {
                        trenewal = asr;
                    }
                } else {
                    trenewal = 0;
                }
            }
            tsubbooking = bd.Total_New_Booking__c + bd.Total_Renewal_Booking__c;
            
            
            objBD.Temp_Annualized_Subscription_Revenue__c = asr;
            objBD.Temp_AddOn_ARR__c = tadd;
            objBD.Temp_Renewal_ARR__c = trenewal;
            objBD.Temp_Total_Bookings__c = tsubbooking;
            bookingDetailsUpdate.add(objBD );
        }
        if(!bookingDetailsUpdate.isEmpty()){
            bookingDetailTriggerHandler_flag = true;
            update bookingDetailsUpdate;
        }
        
    }
    
    /**@@
        #DESCRIPTION     : This method is used to update Booking detail information based on relate Order and Opportunity information
        #Paramaters      : List<Booking_Detail__c> newRecord
        #Return type     : void
    @@**/
    public static void OnBeforeInsert(List<Booking_Detail__c> newRecord) {
        
        set<Id> sOrderId = new set<Id>();
        set<Id> sOppId = new set<Id>();
        
        for(Booking_Detail__c bd : newRecord) {
            if(bd.Order__c != null){
                sOrderId.add(bd.Order__c);
            }
            if(bd.Opportunity__c != null){
                sOppId.add(bd.Opportunity__c);
            }
        }
        // Fetch Existing Order related to Booking Detail
        Map<Id, Order> mapOrderList = new Map<Id, Order>();
        if(!sOrderId.isEmpty()){
            mapOrderList = new Map<Id, Order>([Select Id, Term_Months__c, Free_Months__c, Renewal_Term__c, Total_Subscription_Revenue__c from Order where Id IN: sOrderId]);
        }
        
        // Fetch Existing Opportunity related to Booking Detail
        Map<Id, Opportunity> mapOpportunityList = new Map<Id, Opportunity>();
        if(!sOppId.isEmpty()){
            mapOpportunityList = new Map<Id, Opportunity>([Select Id, Renewal_Term__c, Target_Renewal_ARR__c, SBQQ__PrimaryQuote__r.Id, Total_Subscription_Revenue__c from Opportunity where Id IN: sOppId]);
        }
        
        for(Booking_Detail__c bd : newRecord) {
                        
                                            
            double asr = 0.00;
            double myr = 0.00;
            double tadd = 0.00;
            double trenewal = 0.00;
            double tsubbooking = 0.00;
            double renewalTerm = 0.00;
            double annualTerm = 0.00;
            
            if(bd.Order__c != null && mapOrderList.containsKey(bd.Order__c)){
                Order relatedOrder = mapOrderList.get(bd.Order__c);
                double calculatedTerm = relatedOrder.Term_Months__c - relatedOrder.Free_Months__c;

                if ((calculatedTerm) > 12){
                    renewalTerm = calculatedTerm;
                    annualTerm = 12;
                } else {
                    renewalTerm = 12;
                    annualTerm = calculatedTerm;
                }

            
                asr = (relatedOrder.Total_Subscription_Revenue__c/(calculatedTerm)) * annualTerm;
                myr = (relatedOrder.Total_Subscription_Revenue__c/(calculatedTerm)) * bd.MYR_Term__c;
                bd.Subscription_Term_Months__c = relatedOrder.Term_Months__c;
            }
            
            if(bd.Opportunity__c != null && mapOpportunityList.containsKey(bd.Opportunity__c)){
                Opportunity relatedOpp = mapOpportunityList.get(bd.Opportunity__c);
                if(bd.Is_Add_On_Booking__c) {
                    tadd = asr;
                } else {
                    IF(bd.Is_Renewal_Booking__c) {
                        IF(asr > relatedOpp.Target_Renewal_ARR__c) {
                            tadd = asr - relatedOpp.Target_Renewal_ARR__c;
                            } else {
                                tadd = 0;
                            }
                    } else {
                        tadd = 0;
                    }
                }
                if(bd.Is_Renewal_Booking__c){
                    if((asr - relatedOpp.Target_Renewal_ARR__c) > 0){
                        trenewal = relatedOpp.Target_Renewal_ARR__c;
                    } else {
                        trenewal = asr;
                    }
                } else {
                    trenewal = 0;
                }
            }
            tsubbooking = bd.Total_New_Booking__c + bd.Total_Renewal_Booking__c;
            
            bd.Temp_Annualized_Subscription_Revenue__c = asr;
            bd.Temp_AddOn_ARR__c = tadd;
            bd.Temp_Renewal_ARR__c = trenewal;
            bd.Temp_Total_Bookings__c = tsubbooking;
        }
    }
}