AI-JADEDEVS4/src/objects/Booking_Detail__c.object
<CustomObject>
    <description>Created upon Opportunity Closed-Won
- opp id
- New logo ARR
- Add-on ARR
- total New ARR (New logo ARR + Add- on ARR)
- Service
- Scheduled Renewal ARR (Installments)
- Renewal ARR (Scheduled Renewal ARR+ Contract ARR)
- ACV (Total New ARR + Renewal ARR + Service)
- New MYR
- Renewal MYR
- Total MYR (New MYR + Renewal MYR)
- Total Bookings (Total New ARR + Services + Scheduled Renewal ARR + Total MYR)
- Unbilled
- TCV Bookings (Total Bookings + Unbilled)
- Subscription Start
- Subscription End</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Closed Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking Details</relationshipLabel>
        <relationshipName>Booking_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Booking Detail</label>
    <nameField>
        <displayFormat>Booking-{000000}</displayFormat>
        <label>Booking Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote that generated this contract.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

AI-JADEDEVS4/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <description>The Value In this Field Indicates if this Product is Service or Subscription Revenue</description>
        <inlineHelpText>The Value In this Field Indicates if this Product is Service or Subscription Revenue</inlineHelpText>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionBase__c</fullName>
        <description>Determines whether dynamic subscriptions are calculated off List or Net product price.</description>
        <inlineHelpText>Determines whether dynamic subscriptions are calculated off List or Net product price.</inlineHelpText>
        <label>Percent Of Total Base</label>
        <picklist>
            <picklistValues>
                <fullName>List</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionCategory__c</fullName>
        <description>Subscription category for this product. Applies to all products and used to limit percent of total subscriptions to certain products.</description>
        <inlineHelpText>Use this to limit percent-of-total subscriptions to certain products. For example, software maintenance should only calculate percentage on software products.</inlineHelpText>
        <label>Percent Of Total Category</label>
        <picklist>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionPricing__c</fullName>
        <description>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</description>
        <inlineHelpText>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</inlineHelpText>
        <label>Subscription Pricing</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent Of Total</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
        <inlineHelpText>Term length of this subscription. Only applicable if the product is a subscription.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionType__c</fullName>
        <description>Renewalable Subscriptions will transfer to Renewal Quotes. One-time Subscriptions will not.</description>
        <inlineHelpText>Renewalable Subscriptions will transfer to Renewal Quotes. One-time Subscriptions will not.</inlineHelpText>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>Renewable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>One-time</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AI-JADEDEVS4/src/classes/MigrationUtils.cls
public with sharing class MigrationUtils {
    /*
    Method for creating default standard pricebook entries
    */
    public static List<PricebookEntry> CreateDefaultPricebookEntries(ID pricebookId){
        List<PricebookEntry> pbEntryList = new List<PricebookEntry>();
        
        List<Product2> productList = [SELECT Id, Name FROM Product2 WHERE IsActive=True];
        for(Product2 prod : productList){
            PricebookEntry entry = new PricebookEntry();
            entry.Pricebook2Id = pricebookId;
            entry.Product2Id = prod.Id;
            entry.UnitPrice = 0.0;
            pbEntryList.add(entry);
        }
        insert pbEntryList;
        return pbEntryList;
    }
    
    public static List<Product2> updateProductFamily(){
        List<Product2> products = [SELECT Id,SBQQ__SubscriptionBase__c,SBQQ__SubscriptionPricing__c,SBQQ__SubscriptionCategory__c,SBQQ__SubscriptionTerm__c,SBQQ__SubscriptionType__c,Revenue_Type__c,Family FROM Product2];
        for(Product2 prod : products){
            if(prod.Revenue_Type__c == 'Subscription'){
                prod.Family = 'Subscription';
                prod.SBQQ__SubscriptionBase__c = 'List';
                prod.SBQQ__SubscriptionPricing__c = 'Fixed';
                prod.SBQQ__SubscriptionCategory__c = 'Software';
                prod.SBQQ__SubscriptionTerm__c = 12;
                prod.SBQQ__SubscriptionType__c = 'Renewable';
            } else {
                prod.Family = 'Service';
                prod.SBQQ__SubscriptionBase__c = null;
                prod.SBQQ__SubscriptionPricing__c = null;
                prod.SBQQ__SubscriptionCategory__c = null;
                prod.SBQQ__SubscriptionTerm__c = null;
                prod.SBQQ__SubscriptionType__c = null;
            }
        }
        update products;
        return products;
    }
    
    public static List<Product2> updateProductSubscriptionFields(){
        List<Product2> products = [SELECT Id,SBQQ__SubscriptionBase__c,SBQQ__SubscriptionPricing__c,SBQQ__SubscriptionCategory__c,SBQQ__SubscriptionTerm__c,SBQQ__SubscriptionType__c FROM Product2 WHERE Revenue_Type__c='Subscription'];
        for(Product2 prod : products){
            prod.SBQQ__SubscriptionBase__c = 'List';
            prod.SBQQ__SubscriptionPricing__c = 'Fixed';
            prod.SBQQ__SubscriptionCategory__c = 'Software';
            prod.SBQQ__SubscriptionTerm__c = 12;
            prod.SBQQ__SubscriptionType__c = 'Renewable';
        }
        update products;
        return products;
    }
    
    public static List<Product2> provisionDiscountProducts(){
        List<Product2> discountProducts = new List<Product2>();
        Product2 f1 = new Product2(
                Name = 'Free Months - 1',
                Description = 'Free Month SKU',        
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'Free Months - 1',
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 1,
                SBQQ__SubscriptionType__c = 'One-time',
                IsActive = true);
        discountProducts.add(f1);
        
        Product2 f2 = new Product2(
                Name = 'Free Months - 2',
                Description = 'Free Month SKU',        
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'Free Months - 2',
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 2,
                SBQQ__SubscriptionType__c = 'One-time',
                IsActive = true);
        discountProducts.add(f2);
        
        Product2 f3 = new Product2(
                Name = 'Free Months - 3',
                Description = 'Free Month SKU',
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'Free Months - 3',
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 3,
                SBQQ__SubscriptionType__c = 'One-time',
                IsActive = true);
        discountProducts.add(f3);
        
        Product2 d2 = new Product2(
                Name = 'Multi-Year Subscription Discount - 2 Years',
                Description = 'MultiYear Discount SKU',
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'MYD2',
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 24,
                SBQQ__SubscriptionType__c = 'One-time',
                IsActive = true);
        discountProducts.add(d2);
        
        Product2 d3 = new Product2(
                Name = 'Multi-Year Subscription Discount - 2 Years',
                Description = 'MultiYear Discount SKU',
                Family = 'Subscription',
                Revenue_Type__c = 'Subscription',
                ProductCode = 'MYD3',
                SBQQ__SubscriptionBase__c = 'List',
                SBQQ__SubscriptionPricing__c = 'Fixed',
                SBQQ__SubscriptionCategory__c = 'Software',
                SBQQ__SubscriptionTerm__c = 36,
                SBQQ__SubscriptionType__c = 'One-time',
                IsActive = true);
        discountProducts.add(d3);
        
        insert discountProducts;
        return discountProducts;
    }
    
    public static void cleanAccount(ID accountID){
        List<Opportunity> opportunityList = [SELECT Id FROM Opportunity WHERE AccountId=:accountID];        
        delete opportunityList;
        
        List<Contract> contractList = [SELECT Id,AccountId FROM Contract WHERE AccountId=:accountID];
        delete contractList;
        /*
        List<Booking_Detail__c> bookingDetails = [SELECT Id, Opportunity__c,Opportunity__r.AccountId FROM Booking_Detail__c WHERE Opportunity__r.AccountId=:accountId];
        delete bookingDetails;
        */
        List<SBQQ__Subscription__c> subscriptionList = [SELECT Id,SBQQ__Account__c FROM SBQQ__Subscription__c WHERE SBQQ__Account__c=:accountID];
        delete subscriptionList;
        
        List<SBQQ__Quote__c > quoteList = [SELECT Id,SBQQ__Account__c FROM SBQQ__Quote__c WHERE SBQQ__Account__c=:accountID];
        delete quoteList;
        
        List<SBQQ__QuoteLine__c> quoteLineList = [SELECT Id,SBQQ__Quote__r.SBQQ__Account__c FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__r.SBQQ__Account__c=:accountID];
        delete quoteLineList;
    }
    
    /*
     * Many fields on Product/Pricebook objects cannot be updated.
     * This method purges all Product related data prior to a re-import.
     */
    public static void purgeProducts(){
        List<OpportunityLineItem> lineItems = [SELECT Id FROM OpportunityLineItem];
        DELETE lineItems;
                                
        List<Opportunity> opportunities = [SELECT Id FROM Opportunity];
        DELETE opportunities;
        
        List<PricebookEntry> pricebookEntries = [SELECT Id FROM PricebookEntry];
        DELETE pricebookEntries;
        
        List<Pricebook2> pricebooks = [SELECT Id FROM Pricebook2];
        DELETE pricebooks;
        
        List<Product2> products = [SELECT Id FROM Product2];
        DELETE products;
    }
}