AI-JADEDEVS4/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Status_Dynamic_Content_Created__c</fullName>
        <description>MarOps date/time stamp when Dynamic Content checked</description>
        <inlineHelpText>MarOps date/time stamp when Dynamic Content checked</inlineHelpText>
        <label>Status: Dynamic Content Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_Elq_Campaign_Created__c</fullName>
        <description>MarOps date/time stamp when Elq Campaign created checked</description>
        <inlineHelpText>MarOps date/time stamp when Elq Campaign created checked</inlineHelpText>
        <label>Status: Elq Campaign Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_Email_1_Created__c</fullName>
        <description>MarOps date/time stamp when Email #1 created checked</description>
        <inlineHelpText>MarOps date/time stamp when Email #1 created checked</inlineHelpText>
        <label>Status: Email #1 Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_Emails_2_3_created__c</fullName>
        <description>MarOps date/time stamp when Email #2 &amp; #3 created checked</description>
        <inlineHelpText>MarOps date/time stamp when Email #2 &amp; #3 created checked</inlineHelpText>
        <label>Status: Emails 2-3 created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_ICS_Tested__c</fullName>
        <description>MarOps date/time stamp when ICS Tested checkbox checked</description>
        <inlineHelpText>MarOps date/time stamp when ICS Tested checkbox checked</inlineHelpText>
        <label>Status: ICS Tested</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_In_Production__c</fullName>
        <description>Date/Time stamp when status changes to In Production</description>
        <inlineHelpText>Date/Time stamp when status changes to In Production</inlineHelpText>
        <label>Status: In Production</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_Partner_Email_Sent__c</fullName>
        <description>MarOps date/time stamp when Partner HTML created &amp; sent checked</description>
        <inlineHelpText>MarOps date/time stamp when Partner HTML created &amp; sent checked</inlineHelpText>
        <label>Status: Partner Email Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_Planning__c</fullName>
        <description>Date/Time stamp when the campaign status is changed to Planned</description>
        <inlineHelpText>Date/Time stamp when the campaign status is changed to Planned</inlineHelpText>
        <label>Status: Planning</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_Segment_Created__c</fullName>
        <description>MarOps date/time stamp when Segment created checked</description>
        <inlineHelpText>MarOps date/time stamp when Segment created checked</inlineHelpText>
        <label>Status: Segment Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_Shared_List_Created__c</fullName>
        <description>MarOps date/time stamp when Shared List Created checked</description>
        <inlineHelpText>MarOps date/time stamp when Shared List Created checked</inlineHelpText>
        <label>Status: Shared List Created</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/Campaign_Trigger_Test.cls
/**@@
#CLASS NAME    :  Campaign_Trigger_Test 
#DESCRIPTION   :  This is Test Class which covers the 'Trigger_Campaign_Helper' Class.
@@**/

@istest(SeeAllData=false)
public class Campaign_Trigger_Test{
    public static testmethod void AddCampaignMemberStatusClass_Test (){
        Test.StartTest();                    
        DataFactory.insertCustomSetting(); 
        Set<Id> cmpId = new Set<Id>();
        List<Campaign> CampaignRecords = new List<Campaign>();       
        date mydate = date.parse('05/11/2012');
        CampaignRecords = DataFactory.createCampaignWithStatus('test campaign','Planned',1);
        CampaignRecords = DataFactory.createCampaignWithStatus('test campaign','In Production',1);
        
        
        // Check Date/Time stamp populated correctly with current time stamp - updateCampaignFields Check
        List<Campaign> lstCampaign = [SELECT id, Status_Dynamic_Content_Created__c, Status_Elq_Campaign_Created__c, Status_Email_1_Created__c, Status_Emails_2_3_created__c, Status_ICS_Tested__c, Status_Partner_Email_Sent__c, Status_Segment_Created__c, Status_Shared_List_Created__c , Status_Planning__c, Status_In_Production__c FROM Campaign WHERE ID IN: CampaignRecords LIMIT 1];
        system.assertEquals(lstCampaign[0].Status_Dynamic_Content_Created__c, system.now());
        system.assertEquals(lstCampaign[0].Status_Elq_Campaign_Created__c, system.now());
        system.assertEquals(lstCampaign[0].Status_Email_1_Created__c, system.now());
        system.assertEquals(lstCampaign[0].Status_Emails_2_3_created__c, system.now());
        system.assertEquals(lstCampaign[0].Status_ICS_Tested__c, system.now());
        system.assertEquals(lstCampaign[0].Status_Partner_Email_Sent__c, system.now());
        system.assertEquals(lstCampaign[0].Status_Segment_Created__c, system.now());
        system.assertEquals(lstCampaign[0].Status_Shared_List_Created__c, system.now());
        system.assertEquals(lstCampaign[0].Status_In_Production__c, system.now());
        
        //insert CampaignRecords;                        
        cmpId.add(CampaignRecords [0].Id);             
        Datafactory.createCampaignMemberStatusTestRecord(CampaignRecords[0].id,1);
        update CampaignRecords;
        
        // Check Campaign member status are inserted successfully or not
        List<CampaignMemberStatus> lstCampaignMemberStatus = [SELECT id FROM CampaignMemberStatus WHERE CampaignId in: CampaignRecords];
        system.assertEquals(lstCampaignMemberStatus.size() > 0, true);
        
        
        delete CampaignRecords;
        Test.StopTest();        
  } 
}