AI-JADEDEVS4/src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote that generated this contract.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

AI-JADEDEVS4/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <description>The Value In this Field Indicates if this Product is Service or Subscription Revenue</description>
        <inlineHelpText>The Value In this Field Indicates if this Product is Service or Subscription Revenue</inlineHelpText>
        <label>Revenue Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AI-JADEDEVS4/src/classes/MigrationUtils_Tests.cls
@IsTest
public class MigrationUtils_Tests {

    @TestSetup static void init() {
        
    }
    
    @IsTest public static void testPBEntries(){        
        Product2 testProd = new Product2(Name='Test Product', ProductCode='ProdCode', Family='Subscription', Revenue_Type__c = 'Subscription', IsActive=True);
        insert testProd;
        Id pricebookId = Test.getStandardPricebookId();
        List<PricebookEntry> entries = MigrationUtils.CreateDefaultPricebookEntries(pricebookId);
        System.assert(entries.size() > 0);
        
        List<Product2> products = MigrationUtils.updateProductSubscriptionFields();
        System.assert( products.size() > 0);
        
        products = MigrationUtils.updateProductFamily();
        System.assert( products.size() > 0);
        
        List<Product2> discountProducts = MigrationUtils.provisionDiscountProducts();
        System.assert(discountProducts.size() > 0);
        
        TestData.setup();
        TestData data = new TestData();
        MigrationUtils.cleanAccount( data.TestAccount.Id );
        
        MigrationUtils.purgeProducts();
    }
    
    @IsTest public static void batchDeleteTests(){
        TestData.setup();
        TestData data = new TestData();
        
        Test.startTest();
        String query = 'select id from Opportunity';
        BatchDelete delBatch = new BatchDelete(query);
        Id BatchProcessId = Database.ExecuteBatch(delBatch);
        Test.stopTest();
    }
    
    @IsTest public static void contractConversionTests(){
        TestData.setup();
        TestData data = new TestData();
        
        Test.startTest();
        String query = 'SELECT ' + SObjectUtils.allFields('Opportunity') + ' FROM Opportunity';
        OpportunityContractBatch b = new OpportunityContractBatch(query);
        Contract c = b.toContract( data.TestOpportunity );
        System.assert( c != null);
        
        data.TestOpportunity.ARCHIVE_Subscription_Start_Date__c = Date.today();
        data.TestOpportunity.ARCHIVE_Subscription_End_Date__c = Date.today().addYears(1);
        SBQQ__Quote__c q = b.toQuote( data.TestOpportunity );
        System.assert( q != null );
        
        String soql = 'SELECT ' + SObjectUtils.allFields('OpportunityLineItem') + ' FROM OpportunityLineItem';
        List<OpportunityLineItem> lineItems = Database.query(soql);
        b.getLineItems(data.TestOpportunity, lineItems);
        
        List<SBQQ__QuoteLine__c> quoteLines = b.buildQuoteLinesFromQuote(data.TestQuote, data.TestOpportunity, lineItems);
        
        Id BatchProcessId = Database.ExecuteBatch(b);
        Test.stopTest();
    }
}