AI-JADEDEVS4/src/objects/Content__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/InternalHelpDeskController_Tests.cls
@IsTest
public class InternalHelpDeskController_Tests{

    @IsTest public static void defaultContentTests(){
        InternalHelpDeskController ctrl = new InternalHelpDeskController();
        System.assertEquals('', ctrl.getPageContent() );   
        
        Content__c page = new Content__c();
        page.Name = 'Support Page';
        page.Body__c = 'Test body';
        insert page;
        
        System.assertEquals('Test body', ctrl.getPageContent() );
    }
}