AI-JADEDEVS4/src/objects/Content__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/InternalHelpDeskController.cls
public class InternalHelpDeskController{

    public InternalHelpDeskController(){}
    
    public String getPageContent(){
        String content = '';
        
        List<Content__c> contentList = [SELECT Id, Name, Body__c FROM Content__c WHERE Name='Support Page' LIMIT 1]; // TODO Define record name in custom settings.
        if(contentList.size() > 0){
            content = contentList[0].Body__c;
        }
        
        return content;
    }
}