AI-JADEDEVS4/src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__RenewalForecast__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select to trigger the generation of a renewal opportunity for forecasting purposes. Does not automatically generate a renewal quote.</description>
        <inlineHelpText>Triggers generation of renewal opportunity (no quote) for forecasting purposes.</inlineHelpText>
        <label>Renewal Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Renewal opportunity generated to track the renewal of this contract.</description>
        <inlineHelpText>Renewal opportunity generated to track the renewal of this contract.</inlineHelpText>
        <label>Renewal Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal Contracts</relationshipLabel>
        <relationshipName>RenewedContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/ContractRenewalBatch.cls
global class ContractRenewalBatch implements Database.Batchable<sObject> {
  public static boolean SkipContractTriggers = false;  
  global Database.QueryLocator start(Database.BatchableContext BC) {
    String strEscActivated = String.escapeSingleQuotes('Activated');
    String strEscFalse = String.escapeSingleQuotes('FALSE');  
  //  String strOppType = String.escapeSingleQuotes('Add-On');      
    String query = '';
    if(!test.isRunningTest()){  
    query = 'SELECT Id,Status FROM Contract WHERE Status = \''+ strEscActivated  + '\' AND SBQQ__RenewalForecast__c = FALSE AND SBQQ__RenewalOpportunity__c = NULL AND CREATEDDATE = TODAY';
    }
    else
    {
    query = 'SELECT Id,Status FROM Contract LIMIT 10' ;    
    }
     // String query = 'SELECT Id,Status FROM Contract WHERE Status = \''+ strEscActivated  +'\' AND SBQQ__RenewalForecast__c = FALSE AND SBQQ__RenewalOpportunity__c = NULL' ;
    return Database.getQueryLocator(query);
  }
   
    global void execute(Database.BatchableContext BC, List<Contract> scope) {
    system.debug('****scope****'+scope);
    List<Contract> updateContracts = new List<Contract>();
    for(Contract oContract : scope){            
                updateContracts.add( new Contract(ID=oContract.ID,SBQQ__RenewalForecast__c=true));
    }
        SkipContractTriggers = true;
        if(!test.isRunningTest()){        
            update updateContracts ;
        }
  }    
    
  global void finish(Database.BatchableContext BC) {
        
  }
}