AI-JADEDEVS4/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Partner Contact who submitted the Lead this Contact was converted from.</inlineHelpText>
        <label>Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registration_Status__c</fullName>
        <label>Registration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Partner Contact who submitted this Lead.</inlineHelpText>
        <label>Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Last_Activity_Date__c</fullName>
        <label>Partner Last Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Registration_Status__c</fullName>
        <label>Registration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/BatchExecLeadExpirationNotification.cls
/**@@
#Batch CLASS NAME  : BatchExecLeadExpirationNotification
#DESCRIPTION       : This is Batch class used to send an Email to Lead Owner and Related Contact
from "partners@adaptiveinsights.com" email address for Expiration Notification of Lead.
@@**/
public class BatchExecLeadExpirationNotification implements Database.Batchable<sObject>{
    /**@@
    #DESCRIPTION     : This is start method which return the user records.
    #Paramaters      : (Database.BatchableContext bc) It is a reference to the Database.BatchableContext object 
    @@**/
    public Database.QueryLocator start(Database.BatchableContext bc){
        Date dt = System.today()-1;
        //String query = 'SELECT id, owner.Email, Partner_Contact__c, Partner_Contact__r.Email, IsConverted, Partner_Last_Activity_Date__c, Registration_Status__c FROM Lead WHERE Partner_Last_Activity_Date__c =: dt AND IsConverted= false';
        //For Testing
        set<Id> sLeadId = new set<Id>();
        Date dtToday = System.today();
        sLeadId.add('00Q2F0000017wHJ');
        String query = 'SELECT id, owner.Email, Partner_Contact__c, Partner_Contact__r.Email, IsConverted, Partner_Last_Activity_Date__c, Registration_Status__c FROM Lead WHERE id IN: sLeadId AND Partner_Last_Activity_Date__c !=: dtToday AND IsConverted= false';
        return Database.getQueryLocator(query);
    }//End of start method
    
    /**@@
    #DESCRIPTION     : This is execute method, which is used to send Lead Expiration Notification E-mail to 
    Lead Owner and Related Contact from "partners@adaptiveinsights.com" 
    #Paramaters      :  1)BC (Database.BatchableContext) : It is a reference to the Database.BatchableContext object.
                        2)List<lstLead> lstLead: List of Leads.
    @@**/
    public void execute(Database.BatchableContext bc,List<Lead> lstLead){      
        try{
            EmailTemplate templateIdPartnerExpNotification = [Select id from EmailTemplate where name =: CustomConstants.strPartnerLeadExpirationNotificationTemplate];     
            OrgWideEmailAddress[] owea = [select id ,address from OrgWideEmailAddress where address=: CustomConstants.partnerEmailAddress];
            String[] toAddresses = new String[] {};
            String[] ccAddresses = new String[] {};
            ccAddresses.add(CustomConstants.partnerEmailAddress);
            for(Lead leadVar: lstLead){ 
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                toAddresses = new String[] {};
                toAddresses.add(leadVar.Partner_Contact__r.Email);
                toAddresses.add(leadVar.owner.Email);
                mail.setToAddresses(toAddresses);
                mail.setCCAddresses(ccAddresses);
                mail.setTemplateID(templateIdPartnerExpNotification.id);
                mail.setTargetObjectId(leadVar.Id);
                
                //mail.setWhatId(leadVar.id);
                                        
                mail.setTreatTargetObjectAsRecipient(false);
                mail.setSaveAsActivity(false);
                mail.setOrgWideEmailAddressId(owea.get(0).Id);
                
                //Sending Partner Lead Expiration Notification Email
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                
            }//End of For
        }//End of try
        Catch(exception e){
             ExceptionHandlingEmail.sendEmailonException(e);
        }
    }//End of Execute() method
    
    /**@@
    #DESCRIPTION     :  It is a finish method of batch class. used for None purpose but its required in batch class.
    #Paramaters      :  BC (Database.BatchableContext) : It is a reference to the Database.BatchableContext object 
    @@**/
    public void Finish(Database.BatchableContext bc)
    {
        
    }//End of finish method
}//End of BatchDailySummary class