AI-JADEDEVS4/src/objects/FieldMap__mdt.object
<CustomObject>
    <description>Used in the Order conversion process to map Opportunity fields to other objects (Order, Contract, Renewal Opportunity).</description>
    <fields>
        <fullName>FromField__c</fullName>
        <label>From Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FromObject__c</fullName>
        <label>From Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToField__c</fullName>
        <label>To Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToObject__c</fullName>
        <label>To Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Field Map</label>
    <pluralLabel>Field Maps</pluralLabel>
</CustomObject>

AI-JADEDEVS4/src/classes/FieldMapConfiguration.cls
public class FieldMapConfiguration {
    final public static string ALL_FIELDS = 'Id,Label,DeveloperName,FromObject__c,FromField__c,ToObject__c,ToField__c'; // from FieldMap__mdt';
    
    public static List<FieldMap__mdt> getByFromObject(String fromObject){
        String soql = 'SELECT ' + ALL_FIELDS + ' FROM FieldMap__mdt WHERE FromObject__c=:fromObject';
        return Database.query(soql);
    }
    
    public static List<FieldMap__mdt> getByToObject(String toObject){
        String soql = 'SELECT ' + ALL_FIELDS + ' FROM FieldMap__mdt WHERE ToObject__c=:toObject';
        return Database.query(soql);
    }
    
    public static Map<String,String> getByObjects(String fromObject, String toObject){
        Map<String,String> fieldMap = new Map<String,String>();
        String soql = 'SELECT ' + ALL_FIELDS + ' FROM FieldMap__mdt WHERE FromObject__c=:fromObject AND ToObject__c=:toObject';
        List<FieldMap__mdt> metadata = Database.query(soql);
        for(FieldMap__mdt config : metadata){
            fieldMap.put(config.FromField__c, config.ToField__c);
        }
        return fieldMap;
    }
}