AI-JADEDEVS4/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Old_ID__c</fullName>
        <externalId>true</externalId>
        <label>Old ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Reason_for_Recycled__c</fullName>
        <description>Returns the lead to marketing to fix or wait until prospect re-engages. Must define why you Recycled.</description>
        <inlineHelpText>Returns the lead to marketing to fix or wait until prospect re-engages. Must define why you Recycled.</inlineHelpText>
        <label>Reason for Recycled</label>
        <picklist>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Phone Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Title/Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer With Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add to Lead Nurture Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trial_Created_Date__c</fullName>
        <label>Trial Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X1st_Meeting_Completed_Date__c</fullName>
        <label>1st Meeting Attended Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X1st_Meeting_Scheduled_Date__c</fullName>
        <description>Date 1st Meeting is schedlued</description>
        <inlineHelpText>Enter the date the 1st Meeting is scheduled for</inlineHelpText>
        <label>1st Meeting Scheduled Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/LeadActivityBatch_Tests.cls
/**@@
#Test CLASS NAME   :    LeadActivityBatch_Tests
#DESCRIPTION       :    This is a test class of LeadActivityBatch apex batch class.
@@**/

@IsTest
public class LeadActivityBatch_Tests 
{
    /**@@
    #DESCRIPTION     : It is a testMethod used to create test data for above mentioned batch class.
    #Paramaters      : None
    @@**/
    @IsTest public static void basicTests(){
        TestData.initTriggerSettings();
        Lead l = new Lead();
        l.FirstName = 'Test';
        l.LastName = 'Lead';
        l.Company = 'Test Company';
        l.Email = 'lead@unit.test.com';
        l.Old_ID__c='old_id';
        l.X1st_Meeting_Scheduled_Date__c = Date.today();
        l.x1st_meeting_completed_date__c = Date.today();
        l.trial_created_date__c = Date.today();
        l.reason_for_recycled__c = 'Reason';
        insert l;
        
        Test.startTest();
        LeadActivityBatch batch = new LeadActivityBatch();
        Database.executeBatch(batch);
        Test.stopTest();
        
        Integer i = [SELECT COUNT() FROM Event];
        System.assert(i > 0);
    }//End of test method
    
}//End of test class