AI-JADEDEVS4/src/objects/Log__c.object
<CustomObject>
    <description>For use by Sys Admins and Developers to trace async Apex activities.</description>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <label>ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SObject_Type__c</fullName>
        <label>SObject Type</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{000000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/Logger.cls
public class Logger {
    
    public static Integer clear(){
        List<Log__c> logs = [SELECT Id FROM Log__c];
        Integer count = logs.size();
        delete logs;
        return count;
    }
    
    public static Log__c info(String details){
        // TODO: Check custom setting before inserting (to enable declarative on/off)
        System.debug(details);
        Log__c l = new Log__c( 
            Details__c = details,
            Type__c = 'Info');
        insert l;
        return l;
    }
    
    public static Log__c info(String id, String sobjectType, String subject, String details){
        System.debug(details);
        Log__c l = new Log__c(
                ID__c = id,
                SObject_Type__c = sobjectType,
                Subject__c = subject,
                Type__c = 'Info',
                Details__c = details );
        insert l;
        return l;
    }
    
    public static Log__c error(String id, String sobjectType, String subject, String details){
        System.debug(details);
        Log__c l = new Log__c(
                ID__c = id,
                SObject_Type__c = sobjectType,
                Subject__c = subject,
                Type__c = 'Error',
                Details__c = details );
        insert l;
        return l;
    }
    
    public static Log__c error(String module, MigrationResult result){
        Log__c l = new Log__c(
                ID__c = result.Id,
                SObject_Type__c = result.SObjectType,
                Subject__c = module + ' ' + result.Message,
                Type__c = 'Error',
                Details__c = result.Message );
        insert l;
        return l;
    }
}