AI-JADEDEVS4/src/objects/Log__c.object
<CustomObject>
    <description>For use by Sys Admins and Developers to trace async Apex activities.</description>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{000000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/classes/Logger_Tests.cls
@IsTest
public class Logger_Tests {

    @IsTest public static void basicTests(){
        System.assertEquals(0, Logger.clear());
        Logger.info('log info');
        List<Log__c> logEntries = [SELECT Id, Details__c FROM Log__c];
        System.assertEquals(1, logEntries.size());
        System.assertEquals('log info', logEntries[0].Details__c);
        
        Logger.error('test_id', 'Opportunity', 'Error Subject', 'Error details' );
        logEntries = [SELECT Id, Details__c FROM Log__c];
        System.assertEquals(2, logEntries.size());
        System.assertEquals(2, Logger.clear());
        
        MigrationResult result = new MigrationResult();
        result.Success = false;
        result.Id = 'test_id';
        result.SObjectType = 'Opportunity';
        result.Message = 'Error message';
        
        Log__c l = Logger.error('OrderMigrationStrategy', result);
        System.assert(l != null);
    }
}