AI-JADEDEVS4/src/objects/Trial_Key_History__c.object
<CustomObject>
    <fields>
        <fullName>Trial_Key_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Key Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Trial Key History</relationshipLabel>
        <relationshipName>Trial_Key_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_Key_Status__c</fullName>
        <label>Trial Key Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Trial Key History</label>
    <nameField>
        <displayFormat>TKH-{0000}</displayFormat>
        <label>Trial Key History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trial Key History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AI-JADEDEVS4/src/objects/Trial_Server_URL__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Input_Email__c</fullName>
        <label>Input Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Input_Password__c</fullName>
        <label>Input Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trial Server URL</label>
</CustomObject>

AI-JADEDEVS4/src/classes/TrialKeyWebserviceTest.cls
@isTest
private class TrialKeyWebserviceTest {

  @isTest static void sendRequestWithEmailMetodTestWrapper(){
      TestData.initTriggerSettings();
      
      insert new Trial_Server_URL__c(
                Name = 'Trial Server URL',
                Endpoint__c = 'https://sfdc.adaptiveplanning.com/app',
                Input_Email__c = 'webservice',
                Input_Password__c = 'changeme');

    Lead testLeadOne =  new Lead(
        FirstName = 'test', 
        LastName = 'Lead', 
        Company = 'test Company',
        Email = 'sad@as2w3d.com'
      );
    insert testLeadOne;

    Test.startTest();
      sendRequestMethodTest(testLeadOne.Id);
    Test.stopTest();
  }

  @future(callout=true)
    static void sendRequestMethodTest(Id testLeadId) {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new TrialKeyWebservGenerator());
        
        // Call method to test.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        HttpResponse res = TrialKeyWebservice.sendRequest([SELECT Id, Name, Email, Title, Company, Address, Phone FROM Lead WHERE Id = :testLeadId]);
        
        // Verify response received contains fake values
        String contentType = res.getHeader('Content-Type');
        System.assertEquals(contentType, 'application/x-www-form-urlencoded');
        String actualValue = res.getBody();
        String expectedValue = '<getCompanyFromPool>' +
                              '<result>' +
                                  '<resultText>OK</resultText>' +
                                  '<resultValue>0</resultValue>' +
                                  '<password>ey@ars.id@d</password>' +
                                  '<email>sad@as2w3d.com</email>' +
                              '</result>' +
                          '</getCompanyFromPool>';
        System.assertEquals(actualValue, expectedValue);
        System.assertEquals(200, res.getStatusCode());
    }

  @isTest static void sendRequestWithOutEmailMethodTestWrapper(){
      TestData.initTriggerSettings();
      
      insert new Trial_Server_URL__c(
                Name = 'Trial Server URL',
                Endpoint__c = 'https://sfdc.adaptiveplanning.com/app',
                Input_Email__c = 'webservice',
                Input_Password__c = 'changeme');
        
    Lead testLeadOne =  new Lead(
        FirstName = 'test', 
        LastName = 'Lead', 
        Company = 'test Company'
      );
    insert testLeadOne;

    Test.startTest();
      sendRequestWithOutEmailMethodTest(testLeadOne.Id);
    Test.stopTest();
  }

  @future(callout=true)
    static void sendRequestWithOutEmailMethodTest(Id testLeadId) {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new TrialKeyWebservGenerator());
        
        // Call method to test.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        HttpResponse res = TrialKeyWebservice.sendRequest([SELECT Id, Name, Email, Title, Company, Address, Phone FROM Lead WHERE Id = :testLeadId]);
        
        // Verify response received contains fake values
        String contentType = res.getHeader('Content-Type');
        System.assertEquals(contentType, 'application/x-www-form-urlencoded');
        String actualValue = res.getBody();
        String expectedValue = '<getCompanyFromPool>' +
                                '<result>' +
                                    '<resultText>No email</resultText>' +
                                    '<resultValue>-2</resultValue>' +
                                    '<hitId/>' +
                                '</result>' +
                            '</getCompanyFromPool>';
        System.assertEquals(actualValue, expectedValue);
        System.assertEquals(200, res.getStatusCode());
    }

  @isTest static void getTrialKeyWithOutEmailMethodTest(){
      TestData.initTriggerSettings();
      
      insert new Trial_Server_URL__c(
                Name = 'Trial Server URL',
                Endpoint__c = 'https://sfdc.adaptiveplanning.com/app',
                Input_Email__c = 'webservice',
                Input_Password__c = 'changeme');
        
    Lead testLeadOne =  new Lead(
        FirstName = 'test', 
        LastName = 'Lead', 
        Company = 'test Company'
      );
    insert testLeadOne;

    Test.startTest();
      TrialKeyWebservice.getTrialKey(testLeadOne.Id);
    Test.stopTest();

        List<Trial_Key_History__c> hist = [SELECT Id, Trial_Key_Status__c, Trial_Key_Lead__c FROM Trial_Key_History__c];
        System.assertEquals(1, hist.size());
        System.assertEquals('FAIL', hist.get(0).Trial_Key_Status__c);
        System.assertEquals(testLeadOne.Id, hist.get(0).Trial_Key_Lead__c);
  }
}