AI-JADEDEVS4/src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Enables/disables triggers. Utilized by Apex trigger handler classes.</description>
    <fields>
        <fullName>Account_Trigger_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Account Trigger_Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Trigger_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Lead Trigger Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Settings</label>
</CustomObject>

AI-JADEDEVS4/src/classes/TriggerSettings_Tests.cls
@IsTest
public class TriggerSettings_Tests {

    @IsTest public static void basicTests(){
        TriggerSettings__c defaultSettings = TriggerSettings.defaultSettings();
        System.assert(defaultSettings != null);
        
        List<TriggerSettings__c> settingsList = TriggerSettings__c.getall().values();
		System.assertEquals(0, settingsList.size());
        
        TriggerSettings__c ts = TriggerSettings.get();
        System.assert(ts != null); // Default settings.
        
        TriggerSettings__c settings = new TriggerSettings__c();
        settings.Name = 'Settings';
        settings.Account_Trigger_Enabled__c = true;
        settings.Lead_Trigger_Enabled__c = true;
        insert settings;
        
        System.assertEquals(True, settings.Account_Trigger_Enabled__c);
        System.assertEquals(True, settings.Lead_Trigger_Enabled__c);
        
        Map<String, TriggerSettings__c> settingsMap = TriggerSettings__c.getall();
        System.assertEquals(1, settingsMap.size());
        
        ts = TriggerSettings.get();
        System.assert(ts != null);
        System.assertEquals(True, ts.Account_Trigger_Enabled__c);
        System.assertEquals(True, ts.Lead_Trigger_Enabled__c);
        
        System.assertequals(true, TriggerSettings.get().Lead_Trigger_Enabled__c);
    }
}